# https://github.com/swaywm/swaylock/blob/master/swaylock.1.scd
# Core swaylock colors; no swaylock-effects options or authentication overrides.
font=Google Sans
color=ffffff
inside-color=ffffff
inside-clear-color=ceead6
inside-caps-lock-color=feefc3
inside-ver-color=d2e3fc
inside-wrong-color=fad2cf
line-color=ffffff
line-clear-color=ceead6
line-caps-lock-color=feefc3
line-ver-color=d2e3fc
line-wrong-color=fad2cf
ring-color=174ea6
ring-clear-color=0d652d
ring-caps-lock-color=934900
ring-ver-color=174ea6
ring-wrong-color=a50e0e
text-color=202124
text-clear-color=0d652d
text-caps-lock-color=934900
text-ver-color=174ea6
text-wrong-color=a50e0e
key-hl-color=4285f4
bs-hl-color=a50e0e
caps-lock-key-hl-color=e37400
caps-lock-bs-hl-color=a50e0e
separator-color=ffffff
layout-bg-color=ffffff
layout-border-color=9aa0a6
layout-text-color=202124
