# https://docs.astral.sh/uv/concepts/projects/config/
[project]
name = "fmind-theme"
version = "1.0.0"
requires-python = ">=3.14"

[dependency-groups]
dev = [
    "pyyaml>=6.0.3",
    "prompt-toolkit>=3.0.53",
    "configobj>=5.0.9",
    "tinycss2>=1.5.1",
]

[tool.uv]
package = false

[tool.ruff]
line-length = 120
target-version = "py314"
