#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.13"
# dependencies = ["pyyaml>=6.0.2"]
# ///
"""Render one palette source into a theme file for every tool that takes one.

A palette under palettes/ is the single source of truth. Everything in out/ is
generated, so edit the YAML and re-run; never edit out/ by hand.

    uv run render.py            # render every palette
    uv run render.py --check    # validate only, write nothing
    uv run render.py fmind      # render one palette

The readability contract lives in palette.py and is shared with explore.py, so
what gets designed and what gets shipped cannot drift apart. A palette that
misses it is refused and the run exits non-zero.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from palette import BOLD_ROLES, Palette, PaletteError, audit, contrast, load, mix

ROOT = Path(__file__).parent
PALETTES = ROOT / "palettes"
OUT = ROOT / "out"


# ------------------------------------------------------------------- renderers
# Each takes a Palette and returns (path relative to out/, file contents).
# Adding a tool means adding one function here and one entry in RENDERERS.


def ghostty(p: Palette) -> tuple[str, str]:
    lines = [
        f"# {p.name} — generated by render.py, do not edit",
        f"# source: palettes/{p.source.name}",
        "",
        f"background = {p.ground}",
        f"foreground = {p.text}",
        f"cursor-color = {p.cursor}",
        f"selection-background = {mix(p.ground, p.ansi['green'], 0.22)}",
        f"selection-foreground = {p.ansi['bright_white']}",
    ]
    lines += [f"palette = {i}={p.slot(i)}" for i in range(16)]
    return f"ghostty/{p.slug}", "\n".join(lines) + "\n"


def zellij(p: Palette) -> tuple[str, str]:
    body = "\n".join(
        f'        {key} "{p.ansi[key]}"'
        for key in ("black", "red", "green", "yellow", "blue", "magenta", "cyan", "white")
    )
    return f"zellij/{p.slug}.kdl", (
        f"// {p.name} — generated by render.py, do not edit\n"
        f"// source: palettes/{p.source.name}\n\n"
        "themes {\n"
        f"    {p.slug} {{\n"
        f'        fg "{p.text}"\n'
        f'        bg "{p.ground}"\n'
        f"{body}\n"
        f'        orange "{p.ansi["yellow"]}"\n'
        "    }\n"
        "}\n"
    )


def fish(p: Palette) -> tuple[str, str]:
    """fish names its own roles, so this is where the mapping is explicit.

    It is also the clearest demonstration of the fourteen-role palette: a
    command, its arguments and its flags are three different greens rather than
    one, because they are three different things.

    Bold does the work hue cannot. FiraCode ships a real Bold face and no italic
    at all, so bold is the only attribute axis available - spent on the roles you
    scan for (commands, keywords, errors) rather than the ones you read through.
    """
    a = p.ansi
    pairs = [
        ("normal", p.text, "variable"),
        ("command", a["blue"], "function"),
        ("param", a["bright_blue"], "parameter"),
        ("option", a["bright_magenta"], "builtin"),
        ("keyword", a["magenta"], "keyword"),
        ("quote", a["green"], "string"),
        ("escape", a["bright_green"], "escape"),
        ("redirection", a["cyan"], "type"),
        ("operator", a["bright_cyan"], "property"),
        ("end", a["bright_yellow"], "constant"),
        ("error", a["red"], "error"),
        ("comment", a["bright_black"], "comment"),
        ("autosuggestion", a["bright_black"], "comment"),
        ("cancel", a["bright_red"], "warning"),
        ("cwd", p.text, "variable"),
        ("cwd_root", a["red"], "error"),
        ("user", a["bright_cyan"], "property"),
        ("host", a["cyan"], "type"),
        ("host_remote", a["yellow"], "number"),
    ]
    selection = mix(p.ground, a["green"], 0.22).lstrip("#")
    lines = [
        f"# {p.name} — generated by render.py, do not edit",
        f"# source: palettes/{p.source.name}",
        "",
        "# Syntax highlighting and prompt identity",
    ]
    lines += [
        f"set -g fish_color_{key} {value.lstrip('#')}"
        + (" --bold" if role in BOLD_ROLES else "")
        + f"  # {role}"
        for key, value, role in pairs
    ]
    lines += [
        f"set -g fish_color_selection --background={selection}",
        f"set -g fish_color_search_match --background={selection}",
        "set -g fish_color_valid_path --underline",
        "",
        "# Completion pager",
        f"set -g fish_pager_color_progress {a['bright_black'].lstrip('#')}",
        f"set -g fish_pager_color_prefix {a['cyan'].lstrip('#')} --bold",
        f"set -g fish_pager_color_completion {p.text.lstrip('#')}",
        f"set -g fish_pager_color_description {a['bright_black'].lstrip('#')}",
        f"set -g fish_pager_color_selected_background --background={selection}",
    ]
    return f"fish/{p.slug}.fish", "\n".join(lines) + "\n"


def starship(p: Palette) -> tuple[str, str]:
    a = p.ansi
    return f"starship/{p.slug}.toml", (
        f"# {p.name} — generated by render.py, do not edit\n"
        f"# source: palettes/{p.source.name}\n"
        f"# Merge into ~/.config/starship.toml and set palette = \"{p.slug}\"\n\n"
        f'palette = "{p.slug}"\n\n'
        f"[palettes.{p.slug}]\n"
        f'text = "{p.text}"\n'
        f'green = "{a["green"]}"\n'
        f'bright_green = "{a["bright_green"]}"\n'
        f'red = "{a["red"]}"\n'
        f'orange = "{a["yellow"]}"\n'
        f'blue = "{a["blue"]}"\n'
        f'cyan = "{a["cyan"]}"\n'
        f'gray = "{a["bright_black"]}"\n'
    )


def delta(p: Palette) -> tuple[str, str]:
    """Diff grounds are the palette's own red and green pulled onto the ground."""
    a = p.ansi
    return f"delta/{p.slug}.gitconfig", (
        f"# {p.name} — generated by render.py, do not edit\n"
        f"# source: palettes/{p.source.name}\n"
        "# Include from ~/.gitconfig, or paste into its [delta] section.\n\n"
        "[delta]\n"
        '    syntax-theme = "ansi"\n'
        f'    minus-style = syntax "{mix(p.ground, a["red"], 0.20)}"\n'
        f'    minus-emph-style = syntax "{mix(p.ground, a["red"], 0.38)}"\n'
        f'    plus-style = syntax "{mix(p.ground, a["green"], 0.18)}"\n'
        f'    plus-emph-style = syntax "{mix(p.ground, a["green"], 0.34)}"\n'
        f'    hunk-header-style = "{a["bright_black"]}"\n'
        f'    file-style = "{a["bright_green"]}"\n'
        f'    line-numbers-zero-style = "{a["bright_black"]}"\n'
    )


def k9s(p: Palette) -> tuple[str, str]:
    a = p.ansi
    return f"k9s/{p.slug}.yaml", (
        f"# {p.name} — generated by render.py, do not edit\n"
        f"# source: palettes/{p.source.name}\n"
        "# Docs: https://k9scli.io/topics/skins/\n\n"
        "k9s:\n"
        "  body:\n"
        f'    fgColor: "{p.text}"\n'
        "    bgColor: default\n"
        f'    logoColor: "{a["bright_green"]}"\n'
        "  info:\n"
        f'    fgColor: "{a["cyan"]}"\n'
        f'    sectionColor: "{p.text}"\n'
        "  dialog:\n"
        f'    fgColor: "{p.text}"\n'
        f'    bgColor: "{p.ground}"\n'
        f'    buttonFgColor: "{p.ground}"\n'
        f'    buttonBgColor: "{a["green"]}"\n'
        f'    buttonFocusFgColor: "{p.ground}"\n'
        f'    buttonFocusBgColor: "{a["yellow"]}"\n'
        "  frame:\n"
        "    border:\n"
        f'      fgColor: "{a["bright_black"]}"\n'
        f'      focusColor: "{a["bright_green"]}"\n'
        "    menu:\n"
        f'      fgColor: "{p.text}"\n'
        f'      keyColor: "{a["yellow"]}"\n'
        f'      numKeyColor: "{a["yellow"]}"\n'
        "    crumbs:\n"
        f'      fgColor: "{p.ground}"\n'
        f'      bgColor: "{a["green"]}"\n'
        f'      activeBgColor: "{a["bright_green"]}"\n'
        "    status:\n"
        f'      newColor: "{a["cyan"]}"\n'
        f'      modifyColor: "{a["blue"]}"\n'
        f'      deleteColor: "{a["red"]}"\n'
        f'      portForwardColor: "{a["green"]}"\n'
        f'      activeColor: "{a["bright_green"]}"\n'
        f'      pendingColor: "{a["yellow"]}"\n'
        f'      errorColor: "{a["red"]}"\n'
        "    title:\n"
        f'      fgColor: "{a["bright_green"]}"\n'
        "      bgColor: default\n"
        f'      highlightColor: "{a["yellow"]}"\n'
        "  views:\n"
        "    table:\n"
        f'      fgColor: "{p.text}"\n'
        "      bgColor: default\n"
        "      header:\n"
        f'        fgColor: "{a["cyan"]}"\n'
        "        bgColor: default\n"
        f'        sorterColor: "{a["yellow"]}"\n'
    )


def gh_dash(p: Palette) -> tuple[str, str]:
    a = p.ansi
    return f"gh-dash/{p.slug}.yml", (
        f"# {p.name} — generated by render.py, do not edit\n"
        f"# source: palettes/{p.source.name}\n"
        "# Merge the theme: block into ~/.config/gh-dash/config.yml\n\n"
        "theme:\n"
        "  colors:\n"
        f'    primary: "{a["bright_green"]}"\n'
        f'    secondary: "{a["cyan"]}"\n'
        f'    faint: "{a["bright_black"]}"\n'
        f'    warning: "{a["yellow"]}"\n'
        f'    error: "{a["red"]}"\n'
        f'    success: "{a["green"]}"\n'
    )


def neovim(p: Palette) -> tuple[str, str]:
    """A real colorscheme, not a sixteen-colour fallback.

    Neovim is the one place the fourteen-role palette pays off fully, because
    treesitter distinguishes captures a terminal never can: a call from its
    arguments, a builtin from a user function, an attribute from the object it
    hangs off. Everywhere else those roles have to share an ANSI slot.

    Drops into `colors/` on the runtimepath, so `colorscheme fmind` finds it
    with no plugin. Italic is never set: FiraCode has no italic face.
    """
    a = p.ansi
    r = {role: p.role(role) for role in (
        "variable", "parameter", "property", "function", "builtin", "keyword",
        "type", "string", "escape", "number", "constant", "comment",
        "error", "warning",
    )}
    sel = mix(p.ground, a["green"], 0.20)
    line = mix(p.ground, a["green"], 0.10)
    gutter = mix(p.ground, a["bright_white"], 0.22)

    groups: list[tuple[str, str]] = [
        # editor chrome
        ("Normal", f'{{ fg = "{p.text}", bg = "{p.ground}" }}'),
        ("NormalFloat", f'{{ fg = "{p.text}", bg = "{line}" }}'),
        ("FloatBorder", f'{{ fg = "{r["comment"]}", bg = "{line}" }}'),
        ("CursorLine", f'{{ bg = "{line}" }}'),
        ("CursorLineNr", f'{{ fg = "{r["variable"]}", bold = true }}'),
        ("LineNr", f'{{ fg = "{gutter}" }}'),
        ("Visual", f'{{ bg = "{sel}" }}'),
        ("Search", f'{{ fg = "{p.ground}", bg = "{r["number"]}" }}'),
        ("IncSearch", f'{{ fg = "{p.ground}", bg = "{r["warning"]}" }}'),
        ("MatchParen", f'{{ fg = "{r["warning"]}", bold = true }}'),
        ("Pmenu", f'{{ fg = "{p.text}", bg = "{line}" }}'),
        ("PmenuSel", f'{{ bg = "{sel}", bold = true }}'),
        ("StatusLine", f'{{ fg = "{p.text}", bg = "{line}" }}'),
        ("WinSeparator", f'{{ fg = "{r["comment"]}" }}'),
        ("Whitespace", f'{{ fg = "{gutter}" }}'),
        ("Folded", f'{{ fg = "{r["comment"]}", bg = "{line}" }}'),
        ("Title", f'{{ fg = "{r["function"]}", bold = true }}'),
        ("Directory", f'{{ fg = "{r["function"]}" }}'),
        ("Cursor", f'{{ fg = "{p.ground}", bg = "{p.cursor}" }}'),
        # the fourteen roles, on the legacy groups first
        ("Comment", f'{{ fg = "{r["comment"]}" }}'),
        ("Identifier", f'{{ fg = "{r["variable"]}" }}'),
        ("Function", f'{{ fg = "{r["function"]}", bold = true }}'),
        ("Statement", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        ("Keyword", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        ("Conditional", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        ("Repeat", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        ("Operator", f'{{ fg = "{r["variable"]}" }}'),
        ("Type", f'{{ fg = "{r["type"]}" }}'),
        ("String", f'{{ fg = "{r["string"]}" }}'),
        ("Character", f'{{ fg = "{r["string"]}" }}'),
        ("Number", f'{{ fg = "{r["number"]}" }}'),
        ("Float", f'{{ fg = "{r["number"]}" }}'),
        ("Boolean", f'{{ fg = "{r["constant"]}" }}'),
        ("Constant", f'{{ fg = "{r["constant"]}" }}'),
        ("Special", f'{{ fg = "{r["escape"]}" }}'),
        ("PreProc", f'{{ fg = "{r["builtin"]}" }}'),
        ("Error", f'{{ fg = "{r["error"]}", bold = true }}'),
        ("ErrorMsg", f'{{ fg = "{r["error"]}", bold = true }}'),
        ("WarningMsg", f'{{ fg = "{r["warning"]}" }}'),
        ("Todo", f'{{ fg = "{p.ground}", bg = "{r["warning"]}", bold = true }}'),
        # treesitter captures: the reason this file exists
        ("@variable", f'{{ fg = "{r["variable"]}" }}'),
        ("@variable.parameter", f'{{ fg = "{r["parameter"]}" }}'),
        ("@variable.member", f'{{ fg = "{r["property"]}" }}'),
        ("@property", f'{{ fg = "{r["property"]}" }}'),
        ("@field", f'{{ fg = "{r["property"]}" }}'),
        ("@function", f'{{ fg = "{r["function"]}", bold = true }}'),
        ("@function.call", f'{{ fg = "{r["function"]}", bold = true }}'),
        ("@function.method", f'{{ fg = "{r["function"]}", bold = true }}'),
        ("@function.method.call", f'{{ fg = "{r["function"]}", bold = true }}'),
        ("@function.builtin", f'{{ fg = "{r["builtin"]}" }}'),
        ("@constructor", f'{{ fg = "{r["type"]}" }}'),
        ("@keyword", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        ("@keyword.function", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        ("@keyword.return", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        ("@keyword.import", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        ("@keyword.operator", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        ("@keyword.exception", f'{{ fg = "{r["error"]}", bold = true }}'),
        ("@type", f'{{ fg = "{r["type"]}" }}'),
        ("@type.builtin", f'{{ fg = "{r["type"]}" }}'),
        ("@module", f'{{ fg = "{r["property"]}" }}'),
        ("@string", f'{{ fg = "{r["string"]}" }}'),
        ("@string.escape", f'{{ fg = "{r["escape"]}" }}'),
        ("@string.special", f'{{ fg = "{r["escape"]}" }}'),
        ("@number", f'{{ fg = "{r["number"]}" }}'),
        ("@boolean", f'{{ fg = "{r["constant"]}" }}'),
        ("@constant", f'{{ fg = "{r["constant"]}" }}'),
        ("@constant.builtin", f'{{ fg = "{r["constant"]}" }}'),
        ("@comment", f'{{ fg = "{r["comment"]}" }}'),
        ("@comment.error", f'{{ fg = "{r["error"]}", bold = true }}'),
        ("@comment.warning", f'{{ fg = "{r["warning"]}" }}'),
        ("@punctuation.bracket", f'{{ fg = "{r["variable"]}" }}'),
        ("@punctuation.delimiter", f'{{ fg = "{r["variable"]}" }}'),
        ("@operator", f'{{ fg = "{r["variable"]}" }}'),
        ("@attribute", f'{{ fg = "{r["builtin"]}" }}'),
        # LSP semantic tokens follow the same split
        ("@lsp.type.parameter", f'{{ fg = "{r["parameter"]}" }}'),
        ("@lsp.type.property", f'{{ fg = "{r["property"]}" }}'),
        ("@lsp.type.variable", f'{{ fg = "{r["variable"]}" }}'),
        ("@lsp.type.class", f'{{ fg = "{r["type"]}" }}'),
        ("@lsp.type.function", f'{{ fg = "{r["function"]}", bold = true }}'),
        ("@lsp.type.method", f'{{ fg = "{r["function"]}", bold = true }}'),
        ("@lsp.type.keyword", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        # diagnostics and diffs
        ("DiagnosticError", f'{{ fg = "{r["error"]}" }}'),
        ("DiagnosticWarn", f'{{ fg = "{r["warning"]}" }}'),
        ("DiagnosticInfo", f'{{ fg = "{r["type"]}" }}'),
        ("DiagnosticHint", f'{{ fg = "{r["property"]}" }}'),
        ("DiagnosticOk", f'{{ fg = "{r["string"]}" }}'),
        ("DiagnosticUnderlineError", f'{{ sp = "{r["error"]}", undercurl = true }}'),
        ("DiagnosticUnderlineWarn", f'{{ sp = "{r["warning"]}", undercurl = true }}'),
        ("DiffAdd", f'{{ bg = "{mix(p.ground, a["green"], 0.18)}" }}'),
        ("DiffDelete", f'{{ bg = "{mix(p.ground, a["red"], 0.20)}" }}'),
        ("DiffChange", f'{{ bg = "{mix(p.ground, a["yellow"], 0.14)}" }}'),
        ("DiffText", f'{{ bg = "{mix(p.ground, a["yellow"], 0.30)}" }}'),
        ("Added", f'{{ fg = "{r["string"]}" }}'),
        ("Removed", f'{{ fg = "{r["error"]}" }}'),
        ("Changed", f'{{ fg = "{r["number"]}" }}'),
    ]

    body = "\n".join(f'  ["{name}"] = {spec},' for name, spec in groups)
    terminal = "\n".join(
        f'vim.g.terminal_color_{i} = "{p.slot(i)}"' for i in range(16)
    )
    return f"nvim/colors/{p.slug}.lua", (
        f"-- {p.name} — generated by render.py, do not edit\n"
        f"-- source: palettes/{p.source.name}\n"
        "--\n"
        "-- Drop into colors/ on the runtimepath, then `colorscheme "
        f"{p.slug}`.\n"
        "-- Italic is never set: FiraCode ships no italic face, so it would be\n"
        "-- synthesised by slanting upright glyphs.\n\n"
        'vim.cmd("highlight clear")\n'
        'if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end\n'
        "vim.o.termguicolors = true\n"
        "vim.o.background = \"dark\"\n"
        f'vim.g.colors_name = "{p.slug}"\n\n'
        f"{terminal}\n\n"
        "local groups = {\n"
        f"{body}\n"
        "}\n\n"
        "for name, spec in pairs(groups) do\n"
        "  vim.api.nvim_set_hl(0, name, spec)\n"
        "end\n"
    )


RENDERERS = (ghostty, zellij, fish, starship, delta, k9s, gh_dash, neovim)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("palette", nargs="*", help="palette slugs to render (default: all)")
    parser.add_argument("--check", action="store_true", help="validate only, write nothing")
    args = parser.parse_args()

    sources = sorted(PALETTES.glob("*.yaml"))
    if args.palette:
        wanted = set(args.palette)
        sources = [s for s in sources if s.stem in wanted]
        unknown = wanted - {s.stem for s in sources}
        if unknown:
            print(f"no such palette: {', '.join(sorted(unknown))}", file=sys.stderr)
            return 2
    if not sources:
        print(f"no palettes found in {PALETTES}", file=sys.stderr)
        return 2

    failed = False
    for source in sources:
        try:
            palette = load(source)
        except PaletteError as exc:
            print(f"✘ {source.stem}: {exc}", file=sys.stderr)
            failed = True
            continue

        problems = audit(palette)
        ratio = contrast(palette.text, palette.ground)

        if problems and palette.reference:
            print(f"– {palette.slug}  reference palette, not rendered")
            for problem in problems:
                print(f"    {problem}")
            continue
        if problems:
            failed = True
            print(f"✘ {palette.slug}  text {ratio:.1f}:1")
            for problem in problems:
                print(f"    {problem}")
            continue

        print(f"✔ {palette.slug}  text {ratio:.1f}:1", end="")
        if args.check:
            print()
            continue

        for renderer in RENDERERS:
            rel, content = renderer(palette)
            target = OUT / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
        print(f"  →  {len(RENDERERS)} tool files")

    if failed:
        print("\nSome palettes were rejected; nothing was written for those.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
