#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.13"
# dependencies = ["pyyaml>=6.0.2"]
# ///
"""Render one palette source into a theme file for every tool that takes one.

A palette under palettes/ is the single source of truth. One folder per tool at
the repository root is generated, so edit the YAML and re-run; never edit those
folders by hand.

    uv run render.py            # render every palette
    uv run render.py --check    # validate only, write nothing
    uv run render.py fmind      # render one palette

The readability contract lives in palette.py, and a palette that misses it is
refused rather than rendered, so the run exits non-zero instead of shipping a
terminal that cannot be read.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from palette import (
    ANSI,
    BOLD_ROLES,
    ROLES,
    SLOT_OF,
    Palette,
    PaletteError,
    audit,
    hue,
    lightness,
    load,
    measure,
    mix,
    oklch_hex,
)

ROOT = Path(__file__).parent
PALETTES = ROOT / "palettes"
OUT = ROOT  # one folder per tool, at the root


# ------------------------------------------------------------------- renderers
# Each takes a Palette and returns (path relative to the repo root, file contents).
# Adding a tool means adding one function here and one entry in RENDERERS.


def ghostty(p: Palette) -> tuple[str, str]:
    lines = [
        f"# {p.name} — generated by render.py, do not edit",
        f"# source: palettes/{p.source.name}",
        "",
        f"background = {p.ground}",
        f"foreground = {p.text}",
        f"cursor-color = {p.cursor}",
        f"selection-background = {p.surface('selection')}",
        f"selection-foreground = {p.ansi['bright_white']}",
    ]
    lines += [f"palette = {i}={p.slot(i)}" for i in range(16)]

    # Slots 16-255 are the xterm cube, and a theme that stops at 15 leaves every
    # tool that reaches into it looking untouched. The 6x6x6 cube (16-231) is
    # left alone - tools compute gradients from its structure - but the 24-step
    # greyscale ramp (232-255) is only ever used for "grey", so it is reissued at
    # the same luminance with the theme's own cast. That is what makes lsd's
    # `243` and a dozen other tools pick the theme up for free.
    lines += ["", "# greyscale ramp, at xterm luminance with the theme's cast"]
    lines += [
        f"palette = {232 + i}={oklch_hex(lightness(grey), 0.010, hue(p.role('comment')))}"
        for i, grey in enumerate(f"#{v:02x}{v:02x}{v:02x}" for v in range(8, 239, 10))
    ]
    return f"ghostty/{p.slug}", "\n".join(lines) + "\n"


def zellij(p: Palette) -> tuple[str, str]:
    """The full styling block, not the classic ten colours.

    Handed the ten-colour form, Zellij *derives* its whole UI from it - and the
    two things it derives backgrounds from are `fg` and `green`. In this palette
    that means every unselected tab is a solid block of body green and the
    selected tab and mode chip are solid blocks of the near-white `string`: the
    two brightest colours in the palette, painted as fills, across the top and
    bottom of the screen for the whole session. Nothing on the palette side can
    stop it, because the palette does not get to say where those slots land.

    The named form does. Chrome is chrome: ribbons, lists and table cells sit on
    the same second grounds every other tool uses, `punctuation` carries the text
    you do not read, and the body green is spent on the one ribbon that says
    where you are. The active tab reads as bright green text on a dark chip
    rather than as a lit block, which is both the quieter thing and the more
    phosphor-looking one.

    `frame_unselected` is emitted rather than left out. Zellij falls back to
    `frame_selected` for both, so an unfocused pane is framed exactly like the
    focused one and the frame stops answering the only question it is there for.
    """
    r = {role: p.role(role) for role in ROLES}
    panel, selection = p.surface("panel"), p.surface("selection")

    # One emphasis quartet for everything that is read rather than filled. Zellij
    # spends these on keybinding hints, so they are the four accents that stay
    # legible small: warm first, then the three cool tiers.
    accents = (r["number"], r["type"], r["escape"], r["property"])

    def block(name: str, base: str, background: str | None, emphasis=accents) -> str:
        rows = [f'            base "{base}"']
        if background is not None:
            rows.append(f'            background "{background}"')
        rows += [f'            emphasis_{i} "{c}"' for i, c in enumerate(emphasis)]
        return f"        {name} {{\n" + "\n".join(rows) + "\n        }"

    players = ("keyword", "function", "builtin", "number", "type",
               "constant", "error", "punctuation", "warning", "property")
    multiplayer = "        multiplayer_user_colors {\n" + "\n".join(
        f'            player_{i + 1} "{r[role]}"' for i, role in enumerate(players)
    ) + "\n        }"

    blocks = [
        # the status bar and anything else that is plain text
        block("text_unselected", r["punctuation"], p.ground),
        block("text_selected", p.text, selection),
        # tabs and mode chips: the selected one is the only lit thing up there
        block("ribbon_unselected", r["comment"], panel),
        block("ribbon_selected", p.text, selection),
        # pane frames: focused is green, unfocused recedes, highlight is the
        # orange Zellij already uses for renaming and searching
        block("frame_unselected", r["comment"], None),
        block("frame_selected", r["function"], None),
        block("frame_highlight", r["number"], None),
        # plugin tables and lists
        block("table_title", r["escape"], panel),
        block("table_cell_unselected", r["punctuation"], p.ground),
        block("table_cell_selected", p.text, selection),
        block("list_unselected", r["punctuation"], p.ground),
        block("list_selected", p.text, selection),
        # a command that worked, and one that did not
        block("exit_code_success", r["function"], None),
        block("exit_code_error", r["error"], None),
        multiplayer,
    ]
    return f"zellij/{p.slug}.kdl", (
        f"// {p.name} — generated by render.py, do not edit\n"
        f"// source: palettes/{p.source.name}\n"
        "//\n"
        "// Named styles, not the ten-colour palette form: Zellij derives ribbon\n"
        "// backgrounds from `fg` and `green` in that form, which paints the tab bar\n"
        "// in the two brightest colours the palette has.\n\n"
        "themes {\n"
        f"    {p.slug} {{\n"
        + "\n".join(blocks)
        + "\n    }\n}\n"
    )


def fish(p: Palette) -> tuple[str, str]:
    """fish names its own roles, so this is where the mapping is explicit.

    It is also the clearest demonstration of the fifteen-role palette: a command,
    its arguments and its flags are three different colours rather than one,
    because they are three different things.

    Bold does the work hue cannot. FiraCode ships a real Bold face and no italic
    at all, so bold is the only attribute axis available - spent on the roles you
    scan for (commands, keywords, errors) rather than the ones you read through.
    """
    a = p.ansi
    pairs = [
        ("normal", p.text, "variable"),
        ("command", a["blue"], "function"),
        ("param", a["bright_blue"], "parameter"),
        ("option", a["bright_magenta"], "builtin"),
        ("keyword", a["magenta"], "keyword"),
        ("quote", a["green"], "string"),
        ("escape", a["bright_green"], "escape"),
        ("redirection", a["cyan"], "type"),
        ("operator", a["bright_cyan"], "property"),
        ("end", a["bright_yellow"], "constant"),
        ("error", a["red"], "error"),
        ("comment", a["bright_black"], "comment"),
        ("autosuggestion", a["bright_black"], "comment"),
        ("cancel", a["bright_red"], "warning"),
        ("cwd", p.text, "variable"),
        ("cwd_root", a["red"], "error"),
        ("user", a["bright_cyan"], "property"),
        ("host", a["cyan"], "type"),
        ("host_remote", a["yellow"], "number"),
    ]
    selection = p.surface("selection").lstrip("#")
    lines = [
        f"# {p.name} — generated by render.py, do not edit",
        f"# source: palettes/{p.source.name}",
        "",
        "# Syntax highlighting and prompt identity",
    ]
    lines += [
        f"set -g fish_color_{key} {value.lstrip('#')}"
        + (" --bold" if role in BOLD_ROLES else "")
        + f"  # {role}"
        for key, value, role in pairs
    ]
    lines += [
        f"set -g fish_color_selection --background={selection}",
        f"set -g fish_color_search_match --background={selection}",
        "set -g fish_color_valid_path --underline",
        "",
        "# Completion pager",
        f"set -g fish_pager_color_progress {a['bright_black'].lstrip('#')}",
        f"set -g fish_pager_color_prefix {a['cyan'].lstrip('#')} --bold",
        f"set -g fish_pager_color_completion {p.text.lstrip('#')}",
        f"set -g fish_pager_color_description {a['bright_black'].lstrip('#')}",
        f"set -g fish_pager_color_selected_background --background={selection}",
    ]
    return f"fish/{p.slug}.fish", "\n".join(lines) + "\n"


def starship(p: Palette) -> tuple[str, str]:
    a = p.ansi
    return f"starship/{p.slug}.toml", (
        f"# {p.name} — generated by render.py, do not edit\n"
        f"# source: palettes/{p.source.name}\n"
        f"# Merge into ~/.config/starship.toml and set palette = \"{p.slug}\"\n\n"
        f'palette = "{p.slug}"\n\n'
        f"[palettes.{p.slug}]\n"
        f'text = "{p.text}"\n'
        f'green = "{a["green"]}"\n'
        f'bright_green = "{a["bright_green"]}"\n'
        f'red = "{a["red"]}"\n'
        f'orange = "{a["yellow"]}"\n'
        f'blue = "{a["blue"]}"\n'
        f'cyan = "{a["cyan"]}"\n'
        f'gray = "{a["bright_black"]}"\n'
    )


def delta(p: Palette) -> tuple[str, str]:
    """Diff grounds are the palette's own red and green pulled onto the ground."""
    a = p.ansi
    return f"delta/{p.slug}.gitconfig", (
        f"# {p.name} — generated by render.py, do not edit\n"
        f"# source: palettes/{p.source.name}\n"
        "# Include from ~/.gitconfig, or paste into its [delta] section.\n\n"
        "[delta]\n"
        '    syntax-theme = "ansi"\n'
        f'    minus-style = syntax "{p.surface("minus")}"\n'
        f'    minus-emph-style = syntax "{p.surface("minus_emph")}"\n'
        f'    plus-style = syntax "{p.surface("plus")}"\n'
        f'    plus-emph-style = syntax "{p.surface("plus_emph")}"\n'
        f'    hunk-header-style = "{a["bright_black"]}"\n'
        f'    file-style = "{a["bright_green"]}"\n'
        f'    line-numbers-zero-style = "{a["bright_black"]}"\n'
    )


def k9s(p: Palette) -> tuple[str, str]:
    a = p.ansi
    return f"k9s/{p.slug}.yaml", (
        f"# {p.name} — generated by render.py, do not edit\n"
        f"# source: palettes/{p.source.name}\n"
        "# Docs: https://k9scli.io/topics/skins/\n\n"
        "k9s:\n"
        "  body:\n"
        f'    fgColor: "{p.text}"\n'
        "    bgColor: default\n"
        f'    logoColor: "{a["bright_green"]}"\n'
        "  info:\n"
        f'    fgColor: "{a["cyan"]}"\n'
        f'    sectionColor: "{p.text}"\n'
        "  dialog:\n"
        f'    fgColor: "{p.text}"\n'
        f'    bgColor: "{p.ground}"\n'
        f'    buttonFgColor: "{p.ground}"\n'
        f'    buttonBgColor: "{a["blue"]}"\n'
        f'    buttonFocusFgColor: "{p.ground}"\n'
        f'    buttonFocusBgColor: "{a["yellow"]}"\n'
        "  frame:\n"
        "    border:\n"
        f'      fgColor: "{a["bright_black"]}"\n'
        f'      focusColor: "{a["bright_green"]}"\n'
        "    menu:\n"
        f'      fgColor: "{p.text}"\n'
        f'      keyColor: "{a["yellow"]}"\n'
        f'      numKeyColor: "{a["yellow"]}"\n'
        "    crumbs:\n"
        f'      fgColor: "{p.ground}"\n'
        f'      bgColor: "{a["blue"]}"\n'
        f'      activeBgColor: "{a["bright_green"]}"\n'
        "    status:\n"
        f'      newColor: "{a["cyan"]}"\n'
        f'      modifyColor: "{a["blue"]}"\n'
        f'      deleteColor: "{a["red"]}"\n'
        f'      portForwardColor: "{a["blue"]}"\n'
        f'      activeColor: "{a["bright_green"]}"\n'
        f'      pendingColor: "{a["yellow"]}"\n'
        f'      errorColor: "{a["red"]}"\n'
        "    title:\n"
        f'      fgColor: "{a["bright_green"]}"\n'
        "      bgColor: default\n"
        f'      highlightColor: "{a["yellow"]}"\n'
        "  views:\n"
        "    table:\n"
        f'      fgColor: "{p.text}"\n'
        "      bgColor: default\n"
        "      header:\n"
        f'        fgColor: "{a["cyan"]}"\n'
        "        bgColor: default\n"
        f'        sorterColor: "{a["yellow"]}"\n'
    )


def gh_dash(p: Palette) -> tuple[str, str]:
    a = p.ansi
    return f"gh-dash/{p.slug}.yml", (
        f"# {p.name} — generated by render.py, do not edit\n"
        f"# source: palettes/{p.source.name}\n"
        "# Merge the theme: block into ~/.config/gh-dash/config.yml\n\n"
        "theme:\n"
        "  colors:\n"
        f'    primary: "{a["bright_green"]}"\n'
        f'    secondary: "{a["cyan"]}"\n'
        f'    faint: "{a["bright_black"]}"\n'
        f'    warning: "{a["yellow"]}"\n'
        f'    error: "{a["red"]}"\n'
        f'    success: "{a["blue"]}"\n'
    )


def fzf(p: Palette) -> tuple[str, str]:
    """The one tool that is handed slot numbers instead of colours.

    Everything else here paints its own window and gets the palette's hex. fzf
    draws over whatever is already on the screen, so hex would pin the finder to
    one palette while the terminal around it followed Ghostty. `-1` leaves the
    ground, the body text and the gutter exactly as the terminal has them, and
    the slot numbers put every accent on the same sixteen colours as the shell
    it is covering.

    Read through $FZF_DEFAULT_OPTS_FILE, which is evaluated before
    $FZF_DEFAULT_OPTS, so the shell keeps owning layout and key bindings.
    """
    n = {role: ANSI.index(SLOT_OF[role]) for role in ROLES if SLOT_OF[role] != "text"}
    black = ANSI.index("black")
    groups: list[tuple[str, list[tuple[str, object, str]]]] = [
        ("ground and body, left to the terminal", [
            ("fg", -1, "the terminal's own foreground"),
            ("bg", -1, "transparent over the prompt"),
            ("gutter", -1, "no bar down the left"),
            ("query", -1, "what you typed reads as input"),
        ]),
        ("the current line", [
            ("fg+", -1, "body colour, not an accent"),
            ("bg+", black, "slot 0, the palette's own dark"),
            ("hl", n["escape"], "escape — the matched run"),
            ("hl+", n["escape"], "escape — matched, on the current line"),
        ]),
        ("chrome recedes, the way comments do", [
            ("border", n["comment"], "comment"),
            ("separator", n["comment"], "comment"),
            ("scrollbar", n["comment"], "comment"),
            ("info", n["comment"], "comment"),
            ("disabled", n["comment"], "comment"),
        ]),
        ("what you point at and what you pick", [
            ("prompt", n["keyword"], "keyword"),
            ("pointer", n["constant"], "constant"),
            ("marker", n["parameter"], "parameter"),
            ("spinner", n["property"], "property"),
            ("header", n["type"], "type"),
            ("label", n["type"], "type"),
        ]),
    ]
    width = max(len(f"--color={key}:{value}") for _, entries in groups for key, value, _ in entries)
    lines = [
        f"# {p.name} — generated by render.py, do not edit",
        f"# source: palettes/{p.source.name}",
        "#",
        "# Point fzf at this file with FZF_DEFAULT_OPTS_FILE. Colours are ANSI slot",
        "# numbers so the finder follows the terminal; -1 means 'leave it alone'.",
        "",
        "# base16 first: everything not named below falls back to a palette slot",
        "# rather than to one of fzf's own 256-colour defaults.",
        "--color=base16",
    ]
    for note, entries in groups:
        lines += ["", f"# {note}"]
        lines += [
            f"--color={key}:{value}".ljust(width) + f"  # {why}"
            for key, value, why in entries
        ]
    return f"fzf/{p.slug}.conf", "\n".join(lines) + "\n"


def opencode(p: Palette) -> tuple[str, str]:
    """opencode ships its own palette, so it needs the whole theme, not a hint.

    It is a JSON theme dropped into themes/, selected by name. The syntax half
    maps role for role; the chrome half is built from the same mixes the diff
    backgrounds use, so a panel is the ground with a little green in it rather
    than a grey borrowed from somewhere else.
    """
    defs = {role: p.role(role) for role in ROLES}
    defs |= {
        "ground": p.ground,
        "panel": p.surface("panel"),
        "element": p.surface("selection"),
        "addedBg": p.surface("plus_emph"),
        "removedBg": p.surface("minus_emph"),
        "addedGutter": p.surface("plus"),
        "removedGutter": p.surface("minus"),
    }
    theme = {
        "primary": "escape",
        "secondary": "type",
        "accent": "keyword",
        "error": "error",
        "warning": "warning",
        "success": "string",
        "info": "type",
        "text": "variable",
        "textMuted": "comment",
        "background": "ground",
        "backgroundPanel": "panel",
        "backgroundElement": "element",
        "border": "comment",
        "borderActive": "escape",
        "borderSubtle": "element",
        "diffAdded": "string",
        "diffRemoved": "error",
        "diffContext": "comment",
        "diffHunkHeader": "comment",
        "diffHighlightAdded": "escape",
        "diffHighlightRemoved": "warning",
        "diffAddedBg": "addedBg",
        "diffRemovedBg": "removedBg",
        "diffContextBg": "panel",
        "diffLineNumber": "comment",
        "diffAddedLineNumberBg": "addedGutter",
        "diffRemovedLineNumberBg": "removedGutter",
        "markdownText": "variable",
        "markdownHeading": "function",
        "markdownLink": "type",
        "markdownLinkText": "property",
        "markdownCode": "string",
        "markdownCodeBlock": "variable",
        "markdownBlockQuote": "comment",
        "markdownEmph": "number",
        "markdownStrong": "constant",
        "markdownHorizontalRule": "comment",
        "markdownListItem": "keyword",
        "markdownListEnumeration": "keyword",
        "markdownImage": "builtin",
        "markdownImageText": "property",
        "syntaxComment": "comment",
        "syntaxKeyword": "keyword",
        "syntaxFunction": "function",
        "syntaxVariable": "variable",
        "syntaxString": "string",
        "syntaxNumber": "number",
        "syntaxType": "type",
        "syntaxOperator": "punctuation",
        "syntaxPunctuation": "punctuation",
    }
    document = {
        "$schema": "https://opencode.ai/theme.json",
        "_generated": f"{p.name} — render.py, do not edit; source palettes/{p.source.name}",
        "defs": defs,
        "theme": theme,
    }
    return f"opencode/{p.slug}.json", json.dumps(document, indent=2) + "\n"


def ptpython(p: Palette) -> tuple[str, str]:
    """ptpython takes a prompt_toolkit style dict, so it is shipped as Python.

    A module rather than a config file because that is the only thing ptpython
    reads: config.py imports this next to itself and installs both dicts. The
    keys are prompt_toolkit's, which is why they are spelled `pygments.*` even
    though no pygments theme is involved.
    """
    r = {role: p.role(role) for role in ROLES}
    bold = {role: f"bold {r[role]}" for role in BOLD_ROLES}
    panel = p.surface("panel")
    selected = p.surface("selection")

    code = {
        "pygments": r["variable"],
        "pygments.whitespace": r["comment"],
        "pygments.comment": r["comment"],
        "pygments.comment.preproc": r["builtin"],
        "pygments.keyword": bold["keyword"],
        "pygments.keyword.constant": r["constant"],
        "pygments.keyword.namespace": bold["keyword"],
        "pygments.keyword.type": r["type"],
        "pygments.operator": r["punctuation"],
        "pygments.operator.word": bold["keyword"],
        "pygments.punctuation": r["punctuation"],
        "pygments.name": r["variable"],
        "pygments.name.attribute": r["property"],
        "pygments.name.builtin": r["builtin"],
        "pygments.name.builtin.pseudo": r["builtin"],
        "pygments.name.class": r["type"],
        "pygments.name.constant": r["constant"],
        "pygments.name.decorator": r["builtin"],
        "pygments.name.entity": r["property"],
        "pygments.name.exception": bold["error"],
        "pygments.name.function": bold["function"],
        "pygments.name.label": r["property"],
        "pygments.name.namespace": r["property"],
        "pygments.name.tag": bold["keyword"],
        "pygments.name.variable": r["variable"],
        "pygments.literal.string": r["string"],
        "pygments.literal.string.doc": r["string"],
        "pygments.literal.string.escape": r["escape"],
        "pygments.literal.string.interpol": r["escape"],
        "pygments.literal.string.regex": r["escape"],
        "pygments.literal.number": r["number"],
        "pygments.generic.deleted": r["error"],
        "pygments.generic.inserted": r["string"],
        "pygments.generic.error": bold["error"],
        "pygments.generic.heading": bold["function"],
        "pygments.generic.subheading": bold["keyword"],
        "pygments.generic.output": r["comment"],
        "pygments.generic.prompt": bold["function"],
        "pygments.generic.traceback": r["error"],
        "pygments.error": bold["error"],
    }
    ui = {
        "prompt": bold["function"],
        "prompt.dots": r["comment"],
        "in": bold["function"],
        "in.number": r["comment"],
        "out": r["property"],
        "out.number": r["comment"],
        "control-character": r["escape"],
        "separator": r["comment"],
        "docstring": r["string"],
        "line-number": r["comment"],
        "search-match": f"{p.ground} bg:{r['number']}",
        "selected-text": f"bg:{selected}",
        "completion-menu.completion": f"{p.text} bg:{panel}",
        "completion-menu.completion.current": f"{p.ground} bg:{r['escape']}",
        "completion-menu.meta.completion": f"{r['comment']} bg:{panel}",
        "completion-menu.meta.completion.current": f"{p.ground} bg:{r['property']}",
        "completion.builtin": r["builtin"],
        "completion.keyword": r["keyword"],
        "completion.param": r["parameter"],
        "scrollbar.background": f"bg:{panel}",
        "scrollbar.button": f"bg:{r['comment']}",
        "system-toolbar": r["type"],
        "arg-toolbar": r["type"],
        "arg-toolbar.text": "noinherit",
        "signature-toolbar": f"{p.text} bg:{panel}",
        "signature-toolbar current-name": f"{p.ground} bg:{r['escape']} bold",
        "signature-toolbar operator": f"{r['punctuation']} bold",
        "validation-toolbar": f"{p.ground} bg:{r['error']}",
        "status-toolbar": f"{r['punctuation']} bg:{panel}",
        "status-toolbar.title": "underline",
        "status-toolbar.inputmode": f"{r['constant']} bg:{panel}",
        "status-toolbar.key": f"{r['comment']} bg:{p.ground}",
        "status-toolbar key": f"{r['comment']} bg:{p.ground}",
        "status-toolbar.pythonversion": f"{p.text} bg:{panel} bold",
        "status-toolbar more": r["warning"],
        "status-toolbar.input-mode": r["constant"],
        "status-toolbar.pastemodeon": f"{p.ground} bg:{r['warning']}",
        "status-toolbar paste-mode-on": f"{p.ground} bg:{r['warning']}",
        "record": f"{p.ground} bg:{r['error']}",
        "sidebar": f"{p.text} bg:{panel}",
        "sidebar.title": f"{p.ground} bg:{r['escape']} bold",
        "sidebar.label": f"{p.text} bg:{panel}",
        "sidebar.status": f"{r['punctuation']} bg:{panel}",
        "sidebar.label selected": f"{p.ground} bg:{r['escape']}",
        "sidebar.status selected": f"{p.ground} bg:{r['escape']} bold",
        "sidebar.separator": "underline",
        "sidebar.key": f"{r['constant']} bg:{panel} bold",
        "sidebar.key.description": f"{p.text} bg:{panel}",
        "sidebar.helptext": f"{p.text} bg:{panel}",
        "window-border": r["comment"],
        "window-title": f"{p.ground} bg:{r['escape']}",
        "accept-message": f"{p.ground} bg:{r['string']}",
        "exit-confirmation": f"{p.ground} bg:{r['error']}",
    }

    def block(name: str, mapping: dict[str, str]) -> str:
        body = "\n".join(f'    "{key}": "{value}",' for key, value in mapping.items())
        return f"{name}: dict[str, str] = {{\n{body}\n}}"

    return f"ptpython/{p.slug}.py", (
        f'"""{p.name} — generated by render.py, do not edit.\n\n'
        f"source: palettes/{p.source.name}\n\n"
        "Two prompt_toolkit style dicts. Drop next to ptpython's config.py and\n"
        "hand them to install_code_colorscheme and install_ui_colorscheme.\n"
        "Italic is never set: FiraCode ships no italic face.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        f"NAME = \"{p.slug}\"\n\n"
        f"{block('CODE', code)}\n\n"
        f"{block('UI', ui)}\n"
    )


def neovim(p: Palette) -> tuple[str, str]:
    """A real colorscheme, not a sixteen-colour fallback.

    Neovim is the one place the fifteen-role palette pays off fully, because
    treesitter distinguishes captures a terminal never can: a call from its
    arguments, a builtin from a user function, an attribute from the object it
    hangs off. Everywhere else those roles have to share an ANSI slot.

    Drops into `colors/` on the runtimepath, so `colorscheme fmind` finds it
    with no plugin. Italic is never set: FiraCode has no italic face.
    """
    a = p.ansi
    r = {role: p.role(role) for role in ROLES}
    sel = p.surface("selection")
    line = p.surface("line")
    panel = p.surface("panel")
    gutter = mix(p.ground, a["bright_white"], 0.22)

    groups: list[tuple[str, str]] = [
        # editor chrome
        ("Normal", f'{{ fg = "{p.text}", bg = "{p.ground}" }}'),
        ("NormalFloat", f'{{ fg = "{p.text}", bg = "{panel}" }}'),
        ("FloatBorder", f'{{ fg = "{r["comment"]}", bg = "{panel}" }}'),
        ("CursorLine", f'{{ bg = "{line}" }}'),
        ("CursorLineNr", f'{{ fg = "{r["variable"]}", bold = true }}'),
        ("LineNr", f'{{ fg = "{gutter}" }}'),
        ("Visual", f'{{ bg = "{sel}" }}'),
        ("Search", f'{{ fg = "{p.ground}", bg = "{r["number"]}" }}'),
        ("IncSearch", f'{{ fg = "{p.ground}", bg = "{r["warning"]}" }}'),
        ("MatchParen", f'{{ fg = "{r["warning"]}", bold = true }}'),
        ("Pmenu", f'{{ fg = "{p.text}", bg = "{panel}" }}'),
        ("PmenuSel", f'{{ bg = "{sel}", bold = true }}'),
        ("StatusLine", f'{{ fg = "{p.text}", bg = "{panel}" }}'),
        ("WinSeparator", f'{{ fg = "{r["comment"]}" }}'),
        ("Whitespace", f'{{ fg = "{gutter}" }}'),
        ("Folded", f'{{ fg = "{r["comment"]}", bg = "{panel}" }}'),
        ("ColorColumn", f'{{ bg = "{panel}" }}'),
        ("CursorColumn", f'{{ bg = "{line}" }}'),
        ("SignColumn", f'{{ fg = "{r["comment"]}", bg = "{p.ground}" }}'),
        ("Title", f'{{ fg = "{r["function"]}", bold = true }}'),
        ("Directory", f'{{ fg = "{r["function"]}" }}'),
        ("Cursor", f'{{ fg = "{p.ground}", bg = "{p.cursor}" }}'),
        # the fourteen roles, on the legacy groups first
        ("Comment", f'{{ fg = "{r["comment"]}" }}'),
        ("Identifier", f'{{ fg = "{r["variable"]}" }}'),
        ("Function", f'{{ fg = "{r["function"]}", bold = true }}'),
        ("Statement", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        ("Keyword", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        ("Conditional", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        ("Repeat", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        ("Operator", f'{{ fg = "{r["punctuation"]}" }}'),
        ("Delimiter", f'{{ fg = "{r["punctuation"]}" }}'),
        ("Type", f'{{ fg = "{r["type"]}" }}'),
        ("String", f'{{ fg = "{r["string"]}" }}'),
        ("Character", f'{{ fg = "{r["string"]}" }}'),
        ("Number", f'{{ fg = "{r["number"]}" }}'),
        ("Float", f'{{ fg = "{r["number"]}" }}'),
        ("Boolean", f'{{ fg = "{r["constant"]}" }}'),
        ("Constant", f'{{ fg = "{r["constant"]}" }}'),
        ("Special", f'{{ fg = "{r["escape"]}" }}'),
        ("PreProc", f'{{ fg = "{r["builtin"]}" }}'),
        ("Error", f'{{ fg = "{r["error"]}", bold = true }}'),
        ("ErrorMsg", f'{{ fg = "{r["error"]}", bold = true }}'),
        ("WarningMsg", f'{{ fg = "{r["warning"]}" }}'),
        ("Todo", f'{{ fg = "{p.ground}", bg = "{r["warning"]}", bold = true }}'),
        # treesitter captures: the reason this file exists
        ("@variable", f'{{ fg = "{r["variable"]}" }}'),
        ("@variable.parameter", f'{{ fg = "{r["parameter"]}" }}'),
        ("@variable.member", f'{{ fg = "{r["property"]}" }}'),
        ("@property", f'{{ fg = "{r["property"]}" }}'),
        ("@field", f'{{ fg = "{r["property"]}" }}'),
        ("@function", f'{{ fg = "{r["function"]}", bold = true }}'),
        ("@function.call", f'{{ fg = "{r["function"]}", bold = true }}'),
        ("@function.method", f'{{ fg = "{r["function"]}", bold = true }}'),
        ("@function.method.call", f'{{ fg = "{r["function"]}", bold = true }}'),
        ("@function.builtin", f'{{ fg = "{r["builtin"]}" }}'),
        ("@constructor", f'{{ fg = "{r["type"]}" }}'),
        ("@keyword", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        ("@keyword.function", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        ("@keyword.return", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        ("@keyword.import", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        ("@keyword.operator", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        ("@keyword.exception", f'{{ fg = "{r["error"]}", bold = true }}'),
        ("@type", f'{{ fg = "{r["type"]}" }}'),
        ("@type.builtin", f'{{ fg = "{r["type"]}" }}'),
        ("@module", f'{{ fg = "{r["property"]}" }}'),
        ("@string", f'{{ fg = "{r["string"]}" }}'),
        ("@string.escape", f'{{ fg = "{r["escape"]}" }}'),
        ("@string.special", f'{{ fg = "{r["escape"]}" }}'),
        ("@number", f'{{ fg = "{r["number"]}" }}'),
        ("@boolean", f'{{ fg = "{r["constant"]}" }}'),
        ("@constant", f'{{ fg = "{r["constant"]}" }}'),
        ("@constant.builtin", f'{{ fg = "{r["constant"]}" }}'),
        ("@comment", f'{{ fg = "{r["comment"]}" }}'),
        ("@comment.error", f'{{ fg = "{r["error"]}", bold = true }}'),
        ("@comment.warning", f'{{ fg = "{r["warning"]}" }}'),
        ("@punctuation.bracket", f'{{ fg = "{r["punctuation"]}" }}'),
        ("@punctuation.delimiter", f'{{ fg = "{r["punctuation"]}" }}'),
        ("@punctuation.special", f'{{ fg = "{r["escape"]}" }}'),
        ("@operator", f'{{ fg = "{r["punctuation"]}" }}'),
        ("@attribute", f'{{ fg = "{r["builtin"]}" }}'),
        # markdown, where the palette is the whole interface
        #
        # Six heading levels get six colours rather than six weights of one,
        # descending in prominence: body green, then the cool tiers, then the
        # violet, then the amber, then bone. Only the top two get a bar.
        #
        # Both `@markup.heading.N` and its `.markdown` variant are set, because
        # render-markdown links RenderMarkdownH1 straight at the `.markdown`
        # one, and a highlight link to an undefined group resolves to nothing -
        # the treesitter fallback chain does not apply to a plain link.
        *[
            (f"@markup.heading.{n}{suffix}", spec)
            for n, spec in enumerate(
                (
                    f'{{ fg = "{r["variable"]}", bold = true }}',
                    f'{{ fg = "{r["type"]}", bold = true }}',
                    f'{{ fg = "{r["keyword"]}", bold = true }}',
                    f'{{ fg = "{r["constant"]}", bold = true }}',
                    f'{{ fg = "{r["property"]}" }}',
                    f'{{ fg = "{r["punctuation"]}" }}',
                ),
                start=1,
            )
            for suffix in ("", ".markdown")
        ],
        ("@markup.heading", f'{{ fg = "{r["variable"]}", bold = true }}'),
        ("@markup.strong", f'{{ fg = "{r["variable"]}", bold = true }}'),
        # No italic face exists, so emphasis is carried by hue instead of slant.
        ("@markup.italic", f'{{ fg = "{r["property"]}" }}'),
        ("@markup.strikethrough", f'{{ fg = "{r["comment"]}", strikethrough = true }}'),
        ("@markup.underline", '{ underline = true }'),
        ("@markup.raw", f'{{ fg = "{r["escape"]}" }}'),
        ("@markup.raw.markdown_inline", f'{{ fg = "{r["escape"]}" }}'),
        ("@markup.raw.block", f'{{ fg = "{p.text}" }}'),
        ("@markup.link", f'{{ fg = "{r["parameter"]}" }}'),
        ("@markup.link.label", f'{{ fg = "{r["parameter"]}", underline = true }}'),
        ("@markup.link.label.markdown_inline",
         f'{{ fg = "{r["parameter"]}", underline = true }}'),
        ("@markup.link.url", f'{{ fg = "{r["comment"]}" }}'),
        ("@markup.link.markdown_inline", f'{{ fg = "{r["comment"]}" }}'),
        ("@markup.list", f'{{ fg = "{r["punctuation"]}" }}'),
        ("@markup.list.checked", f'{{ fg = "{r["function"]}", bold = true }}'),
        ("@markup.list.unchecked", f'{{ fg = "{r["punctuation"]}" }}'),
        ("@markup.quote", f'{{ fg = "{r["punctuation"]}" }}'),
        ("@markup.math", f'{{ fg = "{r["number"]}" }}'),
        ("@markup.environment", f'{{ fg = "{r["keyword"]}" }}'),
        ("@label", f'{{ fg = "{r["property"]}" }}'),
        ("@conceal", f'{{ fg = "{r["comment"]}" }}'),
        # the same ladder for a buffer with no parser attached
        ("markdownH1", f'{{ fg = "{r["variable"]}", bold = true }}'),
        ("markdownH2", f'{{ fg = "{r["type"]}", bold = true }}'),
        ("markdownH3", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        ("markdownH4", f'{{ fg = "{r["constant"]}", bold = true }}'),
        ("markdownH5", f'{{ fg = "{r["property"]}" }}'),
        ("markdownH6", f'{{ fg = "{r["punctuation"]}" }}'),
        ("markdownCode", f'{{ fg = "{r["escape"]}" }}'),
        ("markdownCodeBlock", f'{{ fg = "{p.text}" }}'),
        ("markdownLinkText", f'{{ fg = "{r["parameter"]}", underline = true }}'),
        ("markdownUrl", f'{{ fg = "{r["comment"]}" }}'),
        ("markdownListMarker", f'{{ fg = "{r["punctuation"]}" }}'),
        ("markdownRule", f'{{ fg = "{r["comment"]}" }}'),
        ("markdownBold", f'{{ fg = "{r["variable"]}", bold = true }}'),
        ("markdownItalic", f'{{ fg = "{r["property"]}" }}'),
        ("markdownBlockquote", f'{{ fg = "{r["punctuation"]}" }}'),
        # render-markdown.nvim, whose own defaults are the reason markdown
        # looked wrong: it links H1Bg at DiffText, H2Bg at DiffAdd, H3Bg at
        # DiffChange and H4Bg at *DiffDelete*, so an unthemed heading renders
        # as a diff row - a red one at level four. Set every group it reads.
        ("RenderMarkdownH1Bg", f'{{ bg = "{p.surface("heading1")}" }}'),
        ("RenderMarkdownH2Bg", f'{{ bg = "{p.surface("heading2")}" }}'),
        ("RenderMarkdownH3Bg", "{}"),
        ("RenderMarkdownH4Bg", "{}"),
        ("RenderMarkdownH5Bg", "{}"),
        ("RenderMarkdownH6Bg", "{}"),
        ("RenderMarkdownCode", f'{{ bg = "{panel}" }}'),
        ("RenderMarkdownCodeBorder", f'{{ bg = "{panel}" }}'),
        ("RenderMarkdownCodeFallback", f'{{ fg = "{p.text}", bg = "{panel}" }}'),
        ("RenderMarkdownCodeInfo", f'{{ fg = "{r["comment"]}", bg = "{panel}" }}'),
        ("RenderMarkdownCodeInline", f'{{ fg = "{r["escape"]}", bg = "{panel}" }}'),
        ("RenderMarkdownInlineHighlight",
         f'{{ fg = "{p.ground}", bg = "{r["number"]}" }}'),
        ("RenderMarkdownBullet", f'{{ fg = "{r["punctuation"]}" }}'),
        ("RenderMarkdownDash", f'{{ fg = "{r["comment"]}" }}'),
        ("RenderMarkdownQuote", f'{{ fg = "{r["punctuation"]}" }}'),
        ("RenderMarkdownTableHead", f'{{ fg = "{r["property"]}" }}'),
        ("RenderMarkdownTableRow", f'{{ fg = "{r["punctuation"]}" }}'),
        ("RenderMarkdownLink", f'{{ fg = "{r["parameter"]}" }}'),
        ("RenderMarkdownWikiLink", f'{{ fg = "{r["parameter"]}" }}'),
        ("RenderMarkdownLinkTitle", f'{{ fg = "{r["property"]}" }}'),
        ("RenderMarkdownChecked", f'{{ fg = "{r["function"]}", bold = true }}'),
        ("RenderMarkdownUnchecked", f'{{ fg = "{r["punctuation"]}" }}'),
        ("RenderMarkdownTodo", f'{{ fg = "{r["warning"]}" }}'),
        ("RenderMarkdownMath", f'{{ fg = "{r["number"]}" }}'),
        ("RenderMarkdownSign", f'{{ fg = "{r["comment"]}" }}'),
        ("RenderMarkdownIndent", f'{{ fg = "{gutter}" }}'),
        ("RenderMarkdownHtmlComment", f'{{ fg = "{r["comment"]}" }}'),
        # LSP semantic tokens follow the same split
        ("@lsp.type.parameter", f'{{ fg = "{r["parameter"]}" }}'),
        ("@lsp.type.property", f'{{ fg = "{r["property"]}" }}'),
        ("@lsp.type.variable", f'{{ fg = "{r["variable"]}" }}'),
        ("@lsp.type.class", f'{{ fg = "{r["type"]}" }}'),
        ("@lsp.type.function", f'{{ fg = "{r["function"]}", bold = true }}'),
        ("@lsp.type.method", f'{{ fg = "{r["function"]}", bold = true }}'),
        ("@lsp.type.keyword", f'{{ fg = "{r["keyword"]}", bold = true }}'),
        # diagnostics and diffs
        ("DiagnosticError", f'{{ fg = "{r["error"]}" }}'),
        ("DiagnosticWarn", f'{{ fg = "{r["warning"]}" }}'),
        ("DiagnosticInfo", f'{{ fg = "{r["type"]}" }}'),
        ("DiagnosticHint", f'{{ fg = "{r["property"]}" }}'),
        ("DiagnosticOk", f'{{ fg = "{r["function"]}" }}'),
        ("DiagnosticUnderlineError", f'{{ sp = "{r["error"]}", undercurl = true }}'),
        ("DiagnosticUnderlineWarn", f'{{ sp = "{r["warning"]}", undercurl = true }}'),
        ("DiffAdd", f'{{ bg = "{p.surface("plus")}" }}'),
        ("DiffDelete", f'{{ bg = "{p.surface("minus")}" }}'),
        ("DiffChange", f'{{ bg = "{p.surface("change")}" }}'),
        ("DiffText", f'{{ bg = "{p.surface("change_emph")}" }}'),
        ("Added", f'{{ fg = "{r["string"]}" }}'),
        ("Removed", f'{{ fg = "{r["error"]}" }}'),
        ("Changed", f'{{ fg = "{r["number"]}" }}'),
        # mini.icons, which paints the file icon on every LazyVim buffer tab.
        # Left unset, its nine groups link at groups that mean something else:
        # Yellow and Orange both land on DiagnosticWarn, so a Python tab wore
        # the warning colour, and Purple landed on Constant. An icon is not a
        # diagnostic, so the nine are given the palette's own hues outright.
        ("MiniIconsAzure", f'{{ fg = "{r["type"]}" }}'),
        ("MiniIconsBlue", f'{{ fg = "{r["parameter"]}" }}'),
        ("MiniIconsCyan", f'{{ fg = "{r["property"]}" }}'),
        ("MiniIconsGreen", f'{{ fg = "{r["variable"]}" }}'),
        ("MiniIconsGrey", f'{{ fg = "{r["punctuation"]}" }}'),
        ("MiniIconsOrange", f'{{ fg = "{r["number"]}" }}'),
        ("MiniIconsPurple", f'{{ fg = "{r["keyword"]}" }}'),
        ("MiniIconsRed", f'{{ fg = "{r["error"]}" }}'),
        ("MiniIconsYellow", f'{{ fg = "{r["constant"]}" }}'),
    ]

    body = "\n".join(f'  ["{name}"] = {spec},' for name, spec in groups)
    terminal = "\n".join(
        f'vim.g.terminal_color_{i} = "{p.slot(i)}"' for i in range(16)
    )
    return f"nvim/colors/{p.slug}.lua", (
        f"-- {p.name} — generated by render.py, do not edit\n"
        f"-- source: palettes/{p.source.name}\n"
        "--\n"
        "-- Drop into colors/ on the runtimepath, then `colorscheme "
        f"{p.slug}`.\n"
        "-- Italic is never set: FiraCode ships no italic face, so it would be\n"
        "-- synthesised by slanting upright glyphs.\n\n"
        'vim.cmd("highlight clear")\n'
        'if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end\n'
        "vim.o.termguicolors = true\n"
        "vim.o.background = \"dark\"\n"
        f'vim.g.colors_name = "{p.slug}"\n\n'
        f"{terminal}\n\n"
        "local groups = {\n"
        f"{body}\n"
        "}\n\n"
        "for name, spec in pairs(groups) do\n"
        "  vim.api.nvim_set_hl(0, name, spec)\n"
        "end\n"
    )


# ------------------------------------------------------------------- previews
# The README images. SVG rather than a screenshot so they regenerate from the
# palette like everything else, need no browser, and diff as text in review.

# Samples tokenised by role once, so a preview is exactly the palette applied to
# real code rather than an artist's impression of it.
CODE_SAMPLE: list[list[tuple[str, str]]] = [
    [("comment", "# measured on the shipped hex, not the design value")],
    [("keyword", "def "), ("function", "audit"), ("punctuation", "("),
     ("parameter", "pal"), ("punctuation", ": "), ("type", "Palette"),
     ("punctuation", ", "), ("parameter", "cut"), ("punctuation", ": "),
     ("type", "float"), ("punctuation", ") -> "), ("type", "list"),
     ("punctuation", "["), ("type", "str"), ("punctuation", "]:")],
    [("punctuation", "    "), ("variable", "problems"), ("punctuation", ": "),
     ("type", "list"), ("punctuation", "["), ("type", "str"),
     ("punctuation", "] = []")],
    [("punctuation", "    "), ("keyword", "for "), ("variable", "a"),
     ("punctuation", ", "), ("variable", "b"), ("keyword", " in "),
     ("builtin", "combinations"), ("punctuation", "("), ("parameter", "pal"),
     ("punctuation", "."), ("property", "roles"), ("punctuation", ", "),
     ("number", "2"), ("punctuation", "):")],
    [("punctuation", "        "), ("variable", "got"), ("punctuation", " = "),
     ("function", "separation"), ("punctuation", "("), ("parameter", "pal"),
     ("punctuation", "."), ("property", "role"), ("punctuation", "("),
     ("variable", "a"), ("punctuation", "), "), ("parameter", "pal"),
     ("punctuation", "."), ("property", "role"), ("punctuation", "("),
     ("variable", "b"), ("punctuation", "))")],
    [("punctuation", "        "), ("keyword", "if "), ("variable", "got"),
     ("punctuation", " < "), ("constant", "MIN_GAP"), ("punctuation", ":")],
    [("punctuation", "            "), ("variable", "problems"),
     ("punctuation", "."), ("property", "append"), ("punctuation", "("), ("string", 'f"'),
     ("escape", "{"), ("variable", "a"), ("escape", "}"), ("string", "/"),
     ("escape", "{"), ("variable", "b"), ("escape", "}"), ("string", " "),
     ("escape", "{"), ("variable", "got"), ("escape", ":.3f}"),
     ("escape", "\\n"), ("string", '"'), ("punctuation", ")")],
    [("punctuation", "    "), ("keyword", "return "), ("variable", "problems")],
]

SHELL_SAMPLE: list[list[tuple[str, str]]] = [
    [("variable", "~/fmind/theme"), ("comment", " on"), ("number", " \u2387 main"),
     ("punctuation", " "), ("keyword", "\u276f "), ("function", "uv"),
     ("parameter", " run render.py"), ("builtin", " --check")],
    [("string", "\u2714 "), ("punctuation", "fmind  text "), ("number", "15.8"),
     ("punctuation", ":"), ("number", "1"), ("punctuation", "  7 hue families  "),
     ("number", "25"), ("punctuation", "% green")],
    [],
    [("variable", "~/fmind/theme"), ("punctuation", " "), ("keyword", "\u276f "),
     ("function", "rg"), ("builtin", " -n"), ("string", ' "separation"'),
     ("parameter", " palette.py"), ("property", " | "), ("function", "head"),
     ("builtin", " -2"), ("constant", " ;")],
    [("number", "19"), ("punctuation", ":sits SEPARATION_FLOOR, which every pair must clear")],
    [],
    [("variable", "~/fmind/theme"), ("punctuation", " "), ("keyword", "\u276f "),
     ("function", "cat"), ("parameter", " palettes/missing.yaml")],
    [("error", "cat: palettes/missing.yaml: No such file or directory")],
    [("warning", "\u26a0 "), ("punctuation", "generated files are "), ("number", "8"),
     ("punctuation", " behind palettes/fmind.yaml")],
    [],
    [("variable", "~/fmind/theme"), ("punctuation", " "), ("keyword", "\u276f "),
     ("function", "git"), ("parameter", " swi"), ("comment", "tch -c palette/violet")],
]

CELL, LEAD, PAD = 8.4, 22.0, 18.0


def _svg(p: Palette, sample: list[list[tuple[str, str]]], title: str) -> str:
    width = PAD * 2 + CELL * max((sum(len(t) for _, t in line) for line in sample), default=0)
    height = PAD * 2 + LEAD * len(sample)
    rows = []
    for i, line in enumerate(sample):
        spans = "".join(
            f'<tspan fill="{p.role(role)}"'
            + (' font-weight="bold"' if role in BOLD_ROLES else "")
            + f">{text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')}</tspan>"
            for role, text in line
        )
        rows.append(
            f'<text xml:space="preserve" x="{PAD}" y="{PAD + LEAD * i + 15:.1f}">{spans}</text>'
        )
    body = "\n    ".join(rows)
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width:.0f}" height="{height:.0f}" '
        f'viewBox="0 0 {width:.0f} {height:.0f}" role="img" aria-label="{title}">\n'
        f'  <rect width="100%" height="100%" fill="{p.ground}"/>\n'
        f'  <g font-family="FiraCode Nerd Font Mono, Fira Code, DejaVu Sans Mono, monospace" '
        f'font-size="14" font-feature-settings="&apos;liga&apos; 0, &apos;calt&apos; 0">'
        f'\n    {body}\n  </g>\n</svg>\n'
    )


def preview_code(p: Palette) -> tuple[str, str]:
    return f"preview/{p.slug}-code.svg", _svg(p, CODE_SAMPLE, f"{p.name} syntax preview")


def preview_shell(p: Palette) -> tuple[str, str]:
    return f"preview/{p.slug}-shell.svg", _svg(p, SHELL_SAMPLE, f"{p.name} shell preview")


def preview_palette(p: Palette) -> tuple[str, str]:
    """The fifteen roles as labelled swatches."""
    rows = [(r, p.role(r), SLOT_LABEL[r]) for r in ROLES]
    w, h, pad = 560.0, 26.0, 16.0
    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w:.0f}" '
        f'height="{pad * 2 + h * len(rows):.0f}" role="img" aria-label="{p.name} roles">',
        f'  <rect width="100%" height="100%" fill="{p.ground}"/>',
        '  <g font-family="FiraCode Nerd Font Mono, Fira Code, DejaVu Sans Mono, monospace" '
        'font-size="13">',
    ]
    for i, (role, colour, slot) in enumerate(rows):
        y = pad + h * i
        out += [
            f'    <rect x="{pad}" y="{y + 4:.0f}" width="70" height="17" rx="2" fill="{colour}"/>',
            f'    <text x="{pad + 82}" y="{y + 17:.0f}" fill="{p.text}">{role}</text>',
            f'    <text x="{pad + 230}" y="{y + 17:.0f}" fill="{p.role("punctuation")}">{colour}</text>',
            f'    <text x="{pad + 340}" y="{y + 17:.0f}" fill="{p.role("comment")}">{slot}</text>',
        ]
    out += ["  </g>", "</svg>", ""]
    return f"preview/{p.slug}-roles.svg", "\n".join(out)


SLOT_LABEL = {
    "variable": "foreground", "error": "1 red", "string": "2 green",
    "number": "3 yellow", "function": "4 blue", "keyword": "5 magenta",
    "type": "6 cyan", "punctuation": "7 white", "comment": "8 bright black",
    "warning": "9 bright red", "escape": "10 bright green",
    "constant": "11 bright yellow", "parameter": "12 bright blue",
    "builtin": "13 bright magenta", "property": "14 bright cyan",
}


# Every tool that takes a palette, and then the README images. Kept apart so
# the run reports how many tools were themed rather than counting pictures.
TOOLS = (ghostty, zellij, fish, fzf, starship, delta, k9s, gh_dash, opencode,
         ptpython, neovim)
PREVIEWS = (preview_code, preview_shell, preview_palette)
RENDERERS = TOOLS + PREVIEWS


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("palette", nargs="*", help="palette slugs to render (default: all)")
    parser.add_argument("--check", action="store_true", help="validate only, write nothing")
    args = parser.parse_args()

    sources = sorted(PALETTES.glob("*.yaml"))
    if args.palette:
        wanted = set(args.palette)
        sources = [s for s in sources if s.stem in wanted]
        unknown = wanted - {s.stem for s in sources}
        if unknown:
            print(f"no such palette: {', '.join(sorted(unknown))}", file=sys.stderr)
            return 2
    if not sources:
        print(f"no palettes found in {PALETTES}", file=sys.stderr)
        return 2

    failed = False
    for source in sources:
        try:
            palette = load(source)
        except PaletteError as exc:
            print(f"✘ {source.stem}: {exc}", file=sys.stderr)
            failed = True
            continue

        problems = audit(palette)
        if problems:
            failed = True
            print(f"✘ {palette.slug}")
            for problem in problems:
                print(f"    {problem}")
            continue

        m = measure(palette)
        print(f"✔ {palette.slug}  text {m['text_contrast']}:1  "
              f"{m['hue_families']} hue families  {m['green_share']}% green  "
              f"separation {m['min_separation']} ({m['tightest_pair']}, "
              f"{m['slack']:+.3f})", end="")
        if args.check:
            print()
            continue

        for renderer in RENDERERS:
            rel, content = renderer(palette)
            target = OUT / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
        print(f"  →  {len(TOOLS)} tools, {len(PREVIEWS)} previews")

    if failed:
        print("\nSome palettes were rejected; nothing was written for those.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
