# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/
[build-system]
requires = ["hatchling>=1.27,<2"]
build-backend = "hatchling.build"

[project]
name = "thonny-fmind"
version = "1.0.0"
description = "Fmind light UI and syntax themes for Thonny"
requires-python = ">=3.10"
dependencies = ["thonny>=4.1,<6"]
license = "MIT"

[tool.hatch.build.targets.wheel]
packages = ["thonnycontrib"]
