# https://starship.rs/config/#palettes
# Merge into ~/.config/starship.toml and set palette = "fmind"

palette = "fmind"

[palettes.fmind]
text = "#202124"
green = "#0d652d"
bright_green = "#0d652d"
red = "#a50e0e"
orange = "#934900"
blue = "#174ea6"
cyan = "#00636d"
gray = "#595d62"
purple = "#681da8"
magenta = "#681da8"
yellow = "#934900"
white = "#202124"
black = "#202124"
