// https://github.com/kingToolbox/WindTerm
// Native scopes adapted from dracula/windterm; see LICENSE.
{
  "styles": [
    {
      "name": "fold.error",
      "style": {
        "foreground": "#a50e0e"
      }
    },
    {
      "name": "fold.highlight",
      "style": {
        "foreground": "#174ea6"
      }
    },
    {
      "name": "grep.mark",
      "style": {
        "background": "#feefc3",
        "decorationStyle": "roundBox"
      }
    },
    {
      "name": "grep.match",
      "style": {
        "background": "#feefc3",
        "decorationStyle": "roundBox"
      }
    },
    {
      "name": "hex.column",
      "style": {
        "background": "#ffffff, #f1f3f4"
      }
    },
    {
      "name": "hex.division",
      "style": {
        "foreground": "#595d62"
      }
    },
    {
      "name": "line.background",
      "style": {
        "background": "#ffffff"
      }
    },
    {
      "name": "line.caret.command",
      "style": {
        "foreground": "#174ea6"
      }
    },
    {
      "name": "line.caret.local",
      "style": {
        "foreground": "#174ea6"
      }
    },
    {
      "name": "line.caret.normal",
      "style": {
        "foreground": "#174ea6"
      }
    },
    {
      "name": "line.caret.remote",
      "style": {
        "foreground": "#174ea6"
      }
    },
    {
      "name": "line.columnMarker",
      "style": {
        "background": "#9aa0a6"
      }
    },
    {
      "name": "line.highlight",
      "style": {
        "foreground": "#202124",
        "background": "#f1f3f4"
      }
    },
    {
      "name": "line.indentGuide",
      "style": {
        "foreground": "#595d62"
      }
    },
    {
      "name": "line.modified",
      "style": {
        "background": "#feefc3"
      }
    },
    {
      "name": "line.saved",
      "style": {
        "background": "#ceead6"
      }
    },
    {
      "name": "line.unsaved",
      "style": {
        "background": "#feefc3"
      }
    },
    {
      "name": "line.wrapSymbol",
      "style": {
        "foreground": "#174ea6"
      }
    },
    {
      "name": "margin.blank",
      "style": {
        "foreground": "#a50e0e"
      }
    },
    {
      "name": "margin.fold",
      "style": {
        "foreground": "#595d62"
      }
    },
    {
      "name": "margin.number",
      "style": {
        "foreground": "#595d62"
      }
    },
    {
      "name": "margin.symbol",
      "style": {
        "background": "#ffffff"
      }
    },
    {
      "name": "margin.text",
      "style": {
        "background": "#ffffff"
      }
    },
    {
      "name": "margin.timestamp",
      "style": {
        "foreground": "#595d62"
      }
    },
    {
      "name": "pair.error",
      "style": {
        "decorationStyle": "roundBox",
        "decorationForeground": "#a50e0e",
        "decorationBackground": "#fad2cf"
      }
    },
    {
      "name": "pair.highlight",
      "style": {
        "decorationStyle": "roundBox",
        "decorationForeground": "#174ea6",
        "decorationBackground": "#d2e3fc"
      }
    },
    {
      "name": "terminal.ansiBlack",
      "style": {
        "foreground": "#202124"
      }
    },
    {
      "name": "terminal.ansiRed",
      "style": {
        "foreground": "#a50e0e"
      }
    },
    {
      "name": "terminal.ansiGreen",
      "style": {
        "foreground": "#0d652d"
      }
    },
    {
      "name": "terminal.ansiYellow",
      "style": {
        "foreground": "#934900"
      }
    },
    {
      "name": "terminal.ansiBlue",
      "style": {
        "foreground": "#174ea6"
      }
    },
    {
      "name": "terminal.ansiMagenta",
      "style": {
        "foreground": "#681da8"
      }
    },
    {
      "name": "terminal.ansiCyan",
      "style": {
        "foreground": "#00636d"
      }
    },
    {
      "name": "terminal.ansiWhite",
      "style": {
        "foreground": "#202124"
      }
    },
    {
      "name": "terminal.ansiBrightBlack",
      "style": {
        "foreground": "#595d62"
      }
    },
    {
      "name": "terminal.ansiBrightRed",
      "style": {
        "foreground": "#a50e0e"
      }
    },
    {
      "name": "terminal.ansiBrightGreen",
      "style": {
        "foreground": "#0d652d"
      }
    },
    {
      "name": "terminal.ansiBrightYellow",
      "style": {
        "foreground": "#934900"
      }
    },
    {
      "name": "terminal.ansiBrightBlue",
      "style": {
        "foreground": "#174ea6"
      }
    },
    {
      "name": "terminal.ansiBrightMagenta",
      "style": {
        "foreground": "#681da8"
      }
    },
    {
      "name": "terminal.ansiBrightCyan",
      "style": {
        "foreground": "#00636d"
      }
    },
    {
      "name": "terminal.ansiBrightWhite",
      "style": {
        "foreground": "#202124"
      }
    },
    {
      "name": "terminal.text",
      "style": {
        "fontFamily": "GoogleSansCode Nerd Font Mono"
      }
    },
    {
      "name": "terminal.text.1",
      "style": {
        "fontFamily": "GoogleSansCode Nerd Font Mono"
      }
    },
    {
      "name": "terminal.text.2",
      "style": {
        "fontFamily": "GoogleSansCode Nerd Font Mono"
      }
    },
    {
      "name": "terminal.prompt",
      "style": {
        "foreground": "#202124",
        "decorationStyle": "lineBackground",
        "decorationBackground": "#ffffff"
      }
    },
    {
      "name": "text.controlChar",
      "style": {
        "foreground": "#595d62"
      }
    },
    {
      "name": "text.default",
      "style": {
        "foreground": "#202124",
        "background": "#ffffff",
        "fontFamily": "Google Sans Code",
        "fontSize": 10
      }
    },
    {
      "name": "text.folded",
      "style": {
        "foreground": "#202124",
        "background": "#f1f3f4",
        "fontStyle": "",
        "decorationStyle": "roundBox"
      }
    },
    {
      "name": "text.hotSpot",
      "style": {
        "background": "#ffffff",
        "decorationStyle": "solidLine",
        "foreground": "#174ea6"
      }
    },
    {
      "name": "text.inserted",
      "style": {
        "decorationStyle": "roundBox",
        "decorationForeground": "#0d652d",
        "decorationBackground": "#ceead6"
      }
    },
    {
      "name": "text.removed",
      "style": {
        "decorationStyle": "roundBox",
        "decorationForeground": "#a50e0e",
        "decorationBackground": "#fad2cf"
      }
    },
    {
      "name": "text.selection",
      "style": {
        "foreground": "#202124",
        "background": "#d2e3fc",
        "decorationStyle": "roundBox"
      }
    },
    {
      "name": "text.syncEdit",
      "style": {
        "foreground": "#202124",
        "decorationStyle": "box",
        "decorationForeground": "#174ea6"
      }
    },
    {
      "name": "text.whiteSpace",
      "style": {
        "foreground": "#595d62"
      }
    }
  ],
  "scopes": [
    {
      "scope": "number.context.grep",
      "style": {
        "foreground": "#595d62"
      }
    },
    {
      "scope": "file.grep",
      "style": {
        "foreground": "#174ea6"
      }
    },
    {
      "scope": "number.line.grep",
      "style": {
        "foreground": "#934900"
      }
    },
    {
      "scope": "path.grep",
      "style": {
        "foreground": "#595d62",
        "decorationStyle": "lineBackground",
        "decorationBackground": "#ffffff"
      }
    },
    {
      "scope": [
        "meta.embedded",
        "source.groovy.embedded"
      ],
      "style": {
        "background": "#ffffff",
        "foreground": "#202124"
      }
    },
    {
      "name": "Comment",
      "scope": "comment, disabled",
      "style": {
        "foreground": "#595d62"
      }
    },
    {
      "name": "String",
      "scope": "string",
      "style": {
        "foreground": "#0d652d"
      }
    },
    {
      "name": "Punctuation",
      "scope": [
        "punctuation.definition.delimiter.linux",
        "punctuation.definition.block.linux"
      ],
      "style": {
        "foreground": "#202124"
      }
    },
    {
      "name": "Template Definition",
      "scope": [
        "punctuation.definition.template-expression",
        "punctuation.section.embedded"
      ],
      "style": {
        "foreground": "#202124"
      }
    },
    {
      "name": "Reset JavaScript string interpolation expression",
      "scope": [
        "meta.template.expression"
      ],
      "style": {
        "foreground": "#0d652d"
      }
    },
    {
      "name": "Number",
      "scope": "constant.numeric",
      "style": {
        "foreground": "#934900"
      }
    },
    {
      "name": "Built-in constant",
      "scope": "constant.language",
      "style": {
        "foreground": "#934900"
      }
    },
    {
      "name": "User-defined constant",
      "scope": "constant.character, constant.other",
      "style": {
        "foreground": "#934900"
      }
    },
    {
      "name": "Variable",
      "scope": "variable",
      "style": {
        "fontStyle": "",
        "foreground": "#202124"
      }
    },
    {
      "name": "Keyword",
      "scope": "keyword",
      "style": {
        "foreground": "#174ea6"
      }
    },
    {
      "name": "Storage",
      "scope": "storage",
      "style": {
        "fontStyle": "",
        "foreground": "#174ea6"
      }
    },
    {
      "name": "Storage type",
      "scope": "storage.type",
      "style": {
        "fontStyle": "",
        "foreground": "#681da8"
      }
    },
    {
      "name": "Class name",
      "scope": "entity.name.type, entity.name.class",
      "style": {
        "foreground": "#681da8",
        "fontStyle": ""
      }
    },
    {
      "name": "Inherited class",
      "scope": "entity.other.inherited-class",
      "style": {
        "foreground": "#681da8",
        "fontStyle": "",
        "decorationStyle": "solidLine"
      }
    },
    {
      "name": "Function name",
      "scope": "entity.name.function",
      "style": {
        "fontStyle": "",
        "foreground": "#174ea6"
      }
    },
    {
      "name": "Function argument",
      "scope": "variable.parameter",
      "style": {
        "fontStyle": "",
        "foreground": "#202124"
      }
    },
    {
      "name": "Tag name",
      "scope": "entity.name.tag",
      "style": {
        "fontStyle": "",
        "foreground": "#174ea6"
      }
    },
    {
      "name": "Tag attribute",
      "scope": "entity.other.attribute-name",
      "style": {
        "fontStyle": "",
        "foreground": "#174ea6"
      }
    },
    {
      "name": "Library function",
      "scope": "support.function",
      "style": {
        "fontStyle": "",
        "foreground": "#174ea6"
      }
    },
    {
      "name": "Library constant",
      "scope": "support.constant",
      "style": {
        "fontStyle": "",
        "foreground": "#934900"
      }
    },
    {
      "name": "Library class/type",
      "scope": "support.type, support.class",
      "style": {
        "fontStyle": "",
        "foreground": "#681da8"
      }
    },
    {
      "name": "Library variable",
      "scope": "support.other.variable",
      "style": {
        "fontStyle": "",
        "foreground": "#202124"
      }
    },
    {
      "name": "Invalid",
      "scope": "invalid",
      "style": {
        "background": "#fad2cf",
        "fontStyle": "",
        "foreground": "#a50e0e",
        "decorationStyle": "lineEndingBackground",
        "decorationBackground": "#ffffff"
      }
    },
    {
      "name": "Invalid deprecated",
      "scope": "invalid.deprecated, invalid.illegal",
      "style": {
        "foreground": "#a50e0e",
        "background": "#fad2cf"
      }
    },
    {
      "name": "JSON String",
      "scope": "meta.structure.dictionary.json string.quoted.double.json",
      "style": {
        "foreground": "#0d652d"
      }
    },
    {
      "name": "diff.header",
      "scope": "meta.diff, meta.diff.header",
      "style": {
        "foreground": "#174ea6"
      }
    },
    {
      "name": "diff.deleted",
      "scope": "markup.deleted",
      "style": {
        "foreground": "#a50e0e",
        "background": "#fad2cf"
      }
    },
    {
      "name": "diff.inserted",
      "scope": "markup.inserted",
      "style": {
        "foreground": "#0d652d",
        "background": "#ceead6"
      }
    },
    {
      "name": "diff.changed",
      "scope": "markup.changed",
      "style": {
        "foreground": "#934900",
        "background": "#feefc3"
      }
    },
    {
      "scope": "constant.numeric.line-number.find-in-files - match",
      "style": {
        "foreground": "#934900"
      }
    },
    {
      "scope": "entity.name.filename.find-in-files",
      "style": {
        "foreground": "#174ea6"
      }
    },
    {
      "name": "Markup Quote",
      "scope": "markup.quote",
      "style": {
        "foreground": "#681da8"
      }
    },
    {
      "name": "Markup Lists",
      "scope": "markup.list",
      "style": {
        "foreground": "#934900"
      }
    },
    {
      "name": "Markup Styling",
      "scope": "markup.bold, markup.italic",
      "style": {
        "foreground": "#202124"
      }
    },
    {
      "name": "Markup Inline",
      "scope": "markup.inline.raw",
      "style": {
        "fontStyle": "",
        "foreground": "#202124"
      }
    },
    {
      "name": "Markup Headings",
      "scope": "markup.heading",
      "style": {
        "foreground": "#174ea6"
      }
    },
    {
      "name": "Markup Setext Header",
      "scope": "markup.heading.setext",
      "style": {
        "fontStyle": "bold",
        "foreground": "#174ea6"
      }
    },
    {
      "name": "Prompt Line",
      "scope": "prompt.line",
      "style": {
        "decorationStyle": "lineBackground",
        "decorationBackground": "#ffffff",
        "foreground": "#202124"
      }
    },
    {
      "scope": "token.success-token",
      "style": {
        "foreground": "#0d652d"
      }
    },
    {
      "scope": "token.info-token",
      "style": {
        "foreground": "#00636d"
      }
    },
    {
      "scope": "token.warn-token",
      "style": {
        "foreground": "#934900"
      }
    },
    {
      "scope": "token.error-token",
      "style": {
        "foreground": "#a50e0e"
      }
    },
    {
      "scope": "token.debug-token",
      "style": {
        "foreground": "#681da8"
      }
    },
    {
      "name": "this.self",
      "scope": "variable.language",
      "style": {
        "foreground": "#202124"
      }
    },
    {
      "name": "identifier",
      "scope": "identifier.text, meta.function-call",
      "style": {
        "foreground": "#202124"
      }
    }
  ]
}
