-- https://neovim.io/doc/user/syntax.html
--
-- Drop into colors/ on the runtimepath, then `colorscheme fmind`.
-- Upright text is intentional; bold carries structural emphasis.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.termguicolors = true
vim.o.background = "light"
vim.g.colors_name = "fmind"

vim.g.terminal_color_0 = "#202124"
vim.g.terminal_color_1 = "#a50e0e"
vim.g.terminal_color_2 = "#0d652d"
vim.g.terminal_color_3 = "#934900"
vim.g.terminal_color_4 = "#174ea6"
vim.g.terminal_color_5 = "#681da8"
vim.g.terminal_color_6 = "#00636d"
vim.g.terminal_color_7 = "#202124"
vim.g.terminal_color_8 = "#595d62"
vim.g.terminal_color_9 = "#a50e0e"
vim.g.terminal_color_10 = "#0d652d"
vim.g.terminal_color_11 = "#934900"
vim.g.terminal_color_12 = "#174ea6"
vim.g.terminal_color_13 = "#681da8"
vim.g.terminal_color_14 = "#00636d"
vim.g.terminal_color_15 = "#202124"

local groups = {
  ["@character"] = { fg = "#0d652d" },
  ["@character.special"] = { fg = "#174ea6" },
  ["@tag"] = { fg = "#174ea6", bold = true },
  ["@tag.attribute"] = { fg = "#681da8" },
  ["@tag.delimiter"] = { fg = "#202124" },
  ["@diff.plus"] = { fg = "#0d652d" },
  ["@diff.minus"] = { fg = "#a50e0e" },
  ["@diff.delta"] = { fg = "#934900" },
  ["Underlined"] = { fg = "#174ea6", underline = true },
  ["Ignore"] = { fg = "#595d62" },
  ["Tag"] = { fg = "#174ea6", bold = true },
  ["Debug"] = { fg = "#934900" },
  ["SpecialChar"] = { fg = "#174ea6" },
  ["SpecialComment"] = { fg = "#595d62" },
  ["Typedef"] = { fg = "#681da8" },
  ["Exception"] = { fg = "#a50e0e", bold = true },
  ["Macro"] = { fg = "#681da8" },
  ["PreCondit"] = { fg = "#174ea6", bold = true },
  ["Normal"] = { fg = "#202124", bg = "#ffffff" },
  ["NormalFloat"] = { fg = "#202124", bg = "#f1f3f4" },
  ["FloatBorder"] = { fg = "#595d62", bg = "#f1f3f4" },
  ["CursorLine"] = { bg = "#f1f3f4" },
  ["CursorLineNr"] = { fg = "#202124", bold = true },
  ["LineNr"] = { fg = "#595d62" },
  ["Visual"] = { bg = "#d2e3fc" },
  ["Search"] = { fg = "#202124", bg = "#e37400" },
  ["IncSearch"] = { fg = "#202124", bg = "#4285f4" },
  ["MatchParen"] = { fg = "#934900", bold = true },
  ["Pmenu"] = { fg = "#202124", bg = "#f1f3f4" },
  ["PmenuSel"] = { bg = "#d2e3fc", bold = true },
  ["StatusLine"] = { fg = "#202124", bg = "#f1f3f4" },
  ["WinSeparator"] = { fg = "#595d62" },
  ["Whitespace"] = { fg = "#595d62" },
  ["Folded"] = { fg = "#595d62", bg = "#f1f3f4" },
  ["ColorColumn"] = { bg = "#f1f3f4" },
  ["CursorColumn"] = { bg = "#f1f3f4" },
  ["SignColumn"] = { fg = "#595d62", bg = "#ffffff" },
  ["Title"] = { fg = "#174ea6" },
  ["Directory"] = { fg = "#174ea6" },
  ["Cursor"] = { fg = "#202124", bg = "#4285f4" },
  ["NonText"] = { fg = "#595d62" },
  ["EndOfBuffer"] = { fg = "#595d62" },
  ["Conceal"] = { fg = "#595d62" },
  ["SpecialKey"] = { fg = "#595d62" },
  ["CurSearch"] = { fg = "#202124", bg = "#fbbc04" },
  ["Substitute"] = { fg = "#202124", bg = "#e37400" },
  ["ModeMsg"] = { fg = "#202124" },
  ["MoreMsg"] = { fg = "#202124" },
  ["Question"] = { fg = "#202124" },
  ["QuickFixLine"] = { bg = "#d2e3fc" },
  ["MsgArea"] = { fg = "#202124" },
  ["StatusLineNC"] = { fg = "#595d62", bg = "#f1f3f4" },
  ["TabLine"] = { fg = "#595d62", bg = "#f1f3f4" },
  ["TabLineSel"] = { fg = "#202124", bg = "#d2e3fc", bold = true },
  ["TabLineFill"] = { bg = "#ffffff" },
  ["WinBar"] = { fg = "#202124", bg = "#ffffff", bold = true },
  ["WinBarNC"] = { fg = "#595d62", bg = "#ffffff" },
  ["FloatShadow"] = { bg = "#202124", blend = 80 },
  ["FloatShadowThrough"] = { bg = "#202124", blend = 100 },
  ["PmenuSbar"] = { bg = "#f1f3f4" },
  ["PmenuThumb"] = { bg = "#9aa0a6" },
  ["WildMenu"] = { fg = "#202124", bg = "#d2e3fc", bold = true },
  ["SpellBad"] = { sp = "#ea4335", undercurl = true },
  ["SpellCap"] = { sp = "#e37400", undercurl = true },
  ["SpellRare"] = { sp = "#681da8", undercurl = true },
  ["SpellLocal"] = { sp = "#202124", undercurl = true },
  ["Comment"] = { fg = "#595d62" },
  ["Identifier"] = { fg = "#202124" },
  ["@property.yaml"] = { fg = "#174ea6", bold = true },
  ["@property.json"] = { fg = "#174ea6", bold = true },
  ["@property.jsonc"] = { fg = "#174ea6", bold = true },
  ["@property.toml"] = { fg = "#174ea6", bold = true },
  ["yamlMappingKey"] = { fg = "#174ea6", bold = true },
  ["jsonKeyword"] = { fg = "#174ea6", bold = true },
  ["jsonKeywordMatch"] = { fg = "#174ea6", bold = true },
  ["tomlKey"] = { fg = "#174ea6", bold = true },
  ["tomlKeyDq"] = { fg = "#174ea6", bold = true },
  ["tomlKeySq"] = { fg = "#174ea6", bold = true },
  ["yamlPlainScalar"] = { fg = "#0d652d" },
  ["yamlBlockString"] = { fg = "#0d652d" },
  ["Function"] = { fg = "#174ea6" },
  ["Statement"] = { fg = "#174ea6", bold = true },
  ["Keyword"] = { fg = "#174ea6", bold = true },
  ["Conditional"] = { fg = "#174ea6", bold = true },
  ["Repeat"] = { fg = "#174ea6", bold = true },
  ["Operator"] = { fg = "#202124" },
  ["Delimiter"] = { fg = "#202124" },
  ["Type"] = { fg = "#681da8" },
  ["String"] = { fg = "#0d652d" },
  ["Character"] = { fg = "#0d652d" },
  ["Number"] = { fg = "#934900" },
  ["Float"] = { fg = "#934900" },
  ["Boolean"] = { fg = "#934900", bold = true },
  ["Constant"] = { fg = "#934900", bold = true },
  ["Special"] = { fg = "#174ea6" },
  ["PreProc"] = { fg = "#681da8" },
  ["Include"] = { fg = "#174ea6", bold = true },
  ["Define"] = { fg = "#174ea6", bold = true },
  ["StorageClass"] = { fg = "#174ea6", bold = true },
  ["pythonBuiltin"] = { fg = "#681da8" },
  ["pythonDecoratorName"] = { fg = "#681da8" },
  ["pythonExceptions"] = { fg = "#a50e0e" },
  ["pythonBoolean"] = { fg = "#934900", bold = true },
  ["Error"] = { fg = "#a50e0e", bold = true },
  ["ErrorMsg"] = { fg = "#a50e0e", bold = true },
  ["WarningMsg"] = { fg = "#934900" },
  ["Todo"] = { fg = "#202124", bg = "#e37400", bold = true },
  ["@variable"] = { fg = "#202124" },
  ["@variable.parameter"] = { fg = "#202124" },
  ["@variable.member"] = { fg = "#202124" },
  ["@property"] = { fg = "#202124" },
  ["@field"] = { fg = "#202124" },
  ["@function"] = { fg = "#174ea6" },
  ["@function.call"] = { fg = "#174ea6" },
  ["@function.method"] = { fg = "#174ea6" },
  ["@function.method.call"] = { fg = "#174ea6" },
  ["@function.builtin"] = { fg = "#681da8" },
  ["@constructor"] = { fg = "#681da8" },
  ["@keyword"] = { fg = "#174ea6", bold = true },
  ["@keyword.function"] = { fg = "#174ea6", bold = true },
  ["@keyword.return"] = { fg = "#174ea6", bold = true },
  ["@keyword.import"] = { fg = "#174ea6", bold = true },
  ["@keyword.operator"] = { fg = "#174ea6", bold = true },
  ["@keyword.exception"] = { fg = "#a50e0e", bold = true },
  ["@type"] = { fg = "#681da8" },
  ["@type.builtin"] = { fg = "#681da8" },
  ["@module"] = { fg = "#202124" },
  ["@string"] = { fg = "#0d652d" },
  ["@string.escape"] = { fg = "#174ea6" },
  ["@string.special"] = { fg = "#174ea6" },
  ["@number"] = { fg = "#934900" },
  ["@boolean"] = { fg = "#934900", bold = true },
  ["@constant"] = { fg = "#934900", bold = true },
  ["@constant.builtin"] = { fg = "#934900", bold = true },
  ["@comment"] = { fg = "#595d62" },
  ["@comment.error"] = { fg = "#a50e0e", bold = true },
  ["@comment.warning"] = { fg = "#934900" },
  ["@punctuation.bracket"] = { fg = "#202124" },
  ["@punctuation.delimiter"] = { fg = "#202124" },
  ["@punctuation.special"] = { fg = "#174ea6" },
  ["@punctuation.special.markdown"] = { fg = "#202124" },
  ["@punctuation.special.markdown_inline"] = { fg = "#202124" },
  ["@operator"] = { fg = "#202124" },
  ["@attribute"] = { fg = "#681da8" },
  ["@markup.heading.1"] = { fg = "#174ea6", bold = true },
  ["@markup.heading.1.markdown"] = { fg = "#174ea6", bold = true },
  ["@markup.heading.2"] = { fg = "#0d652d", bold = true },
  ["@markup.heading.2.markdown"] = { fg = "#0d652d", bold = true },
  ["@markup.heading.3"] = { fg = "#681da8", bold = true },
  ["@markup.heading.3.markdown"] = { fg = "#681da8", bold = true },
  ["@markup.heading.4"] = { fg = "#202124", bold = true },
  ["@markup.heading.4.markdown"] = { fg = "#202124", bold = true },
  ["@markup.heading.5"] = { fg = "#202124" },
  ["@markup.heading.5.markdown"] = { fg = "#202124" },
  ["@markup.heading.6"] = { fg = "#595d62" },
  ["@markup.heading.6.markdown"] = { fg = "#595d62" },
  ["@markup.heading"] = { fg = "#174ea6", bold = true },
  ["@markup.strong"] = { fg = "#202124", bold = true },
  ["@markup.italic"] = { fg = "#681da8" },
  ["@markup.strikethrough"] = { fg = "#595d62", strikethrough = true },
  ["@markup.underline"] = { fg = "#202124", underline = true },
  ["@markup.raw"] = { fg = "#174ea6" },
  ["@markup.raw.markdown_inline"] = { fg = "#174ea6" },
  ["@markup.raw.block"] = { fg = "#202124" },
  ["@markup.link"] = { fg = "#202124" },
  ["@markup.link.label"] = { fg = "#202124", underline = true },
  ["@markup.link.label.markdown_inline"] = { fg = "#202124", underline = true },
  ["@markup.link.url"] = { fg = "#595d62" },
  ["@markup.link.markdown_inline"] = { fg = "#595d62" },
  ["@markup.list"] = { fg = "#202124" },
  ["@markup.list.checked"] = { fg = "#0d652d", bold = true },
  ["@markup.list.unchecked"] = { fg = "#202124" },
  ["@markup.quote"] = { fg = "#202124" },
  ["@markup.math"] = { fg = "#934900" },
  ["@markup.environment"] = { fg = "#174ea6" },
  ["@label"] = { fg = "#202124" },
  ["@conceal"] = { fg = "#595d62" },
  ["markdownH1"] = { fg = "#174ea6", bold = true },
  ["markdownH2"] = { fg = "#0d652d", bold = true },
  ["markdownH3"] = { fg = "#681da8", bold = true },
  ["markdownH4"] = { fg = "#202124", bold = true },
  ["markdownH5"] = { fg = "#202124" },
  ["markdownH6"] = { fg = "#595d62" },
  ["markdownCode"] = { fg = "#174ea6" },
  ["markdownCodeBlock"] = { fg = "#202124" },
  ["markdownLinkText"] = { fg = "#202124", underline = true },
  ["markdownUrl"] = { fg = "#595d62" },
  ["markdownListMarker"] = { fg = "#202124" },
  ["markdownRule"] = { fg = "#595d62" },
  ["markdownBold"] = { fg = "#202124", bold = true },
  ["markdownItalic"] = { fg = "#681da8" },
  ["markdownBlockquote"] = { fg = "#202124" },
  ["RenderMarkdownH1Bg"] = { bg = "#ffffff" },
  ["RenderMarkdownH2Bg"] = { bg = "#ffffff" },
  ["RenderMarkdownH3Bg"] = {},
  ["RenderMarkdownH4Bg"] = {},
  ["RenderMarkdownH5Bg"] = {},
  ["RenderMarkdownH6Bg"] = {},
  ["RenderMarkdownCode"] = { bg = "#f1f3f4" },
  ["RenderMarkdownCodeBorder"] = { bg = "#f1f3f4" },
  ["RenderMarkdownCodeFallback"] = { fg = "#202124", bg = "#f1f3f4" },
  ["RenderMarkdownCodeInfo"] = { fg = "#595d62", bg = "#f1f3f4" },
  ["RenderMarkdownCodeInline"] = { fg = "#174ea6", bg = "#f1f3f4" },
  ["RenderMarkdownInlineHighlight"] = { fg = "#202124", bg = "#e37400" },
  ["RenderMarkdownBullet"] = { fg = "#202124" },
  ["RenderMarkdownDash"] = { fg = "#595d62" },
  ["RenderMarkdownQuote"] = { fg = "#202124" },
  ["RenderMarkdownTableHead"] = { fg = "#202124" },
  ["RenderMarkdownTableRow"] = { fg = "#202124" },
  ["RenderMarkdownLink"] = { fg = "#202124" },
  ["RenderMarkdownWikiLink"] = { fg = "#202124" },
  ["RenderMarkdownLinkTitle"] = { fg = "#202124" },
  ["RenderMarkdownChecked"] = { fg = "#0d652d", bold = true },
  ["RenderMarkdownUnchecked"] = { fg = "#202124" },
  ["RenderMarkdownTodo"] = { fg = "#934900" },
  ["RenderMarkdownMath"] = { fg = "#934900" },
  ["RenderMarkdownSign"] = { fg = "#595d62" },
  ["RenderMarkdownIndent"] = { fg = "#595d62" },
  ["RenderMarkdownHtmlComment"] = { fg = "#595d62" },
  ["DiagnosticError"] = { fg = "#a50e0e" },
  ["DiagnosticWarn"] = { fg = "#934900" },
  ["DiagnosticInfo"] = { fg = "#00636d" },
  ["DiagnosticHint"] = { fg = "#202124" },
  ["DiagnosticOk"] = { fg = "#0d652d" },
  ["DiagnosticUnderlineError"] = { sp = "#ea4335", undercurl = true },
  ["DiagnosticUnderlineWarn"] = { sp = "#e37400", undercurl = true },
  ["DiagnosticUnderlineInfo"] = { sp = "#00636d", undercurl = true },
  ["DiagnosticUnderlineHint"] = { sp = "#202124", undercurl = true },
  ["DiagnosticUnderlineOk"] = { sp = "#34a853", undercurl = true },
  ["DiagnosticDeprecated"] = { sp = "#9aa0a6", strikethrough = true },
  ["DiagnosticUnnecessary"] = { fg = "#595d62" },
  ["DiffAdd"] = { bg = "#ceead6" },
  ["DiffDelete"] = { bg = "#fad2cf" },
  ["DiffChange"] = { bg = "#feefc3" },
  ["DiffText"] = { fg = "#202124", bg = "#fbbc04", bold = true },
  ["Added"] = { fg = "#0d652d" },
  ["Removed"] = { fg = "#a50e0e" },
  ["Changed"] = { fg = "#934900" },
  ["GitSignsCurrentLineBlame"] = { fg = "#595d62" },
  ["GitSignsAdd"] = { fg = "#0d652d" },
  ["GitSignsAddNr"] = { fg = "#0d652d" },
  ["GitSignsAddCul"] = { fg = "#0d652d" },
  ["GitSignsChange"] = { fg = "#934900" },
  ["GitSignsChangeNr"] = { fg = "#934900" },
  ["GitSignsChangeCul"] = { fg = "#934900" },
  ["GitSignsChangedelete"] = { fg = "#934900" },
  ["GitSignsChangedeleteNr"] = { fg = "#934900" },
  ["GitSignsChangedeleteCul"] = { fg = "#934900" },
  ["GitSignsDelete"] = { fg = "#a50e0e" },
  ["GitSignsDeleteNr"] = { fg = "#a50e0e" },
  ["GitSignsDeleteCul"] = { fg = "#a50e0e" },
  ["GitSignsTopdelete"] = { fg = "#a50e0e" },
  ["GitSignsTopdeleteNr"] = { fg = "#a50e0e" },
  ["GitSignsTopdeleteCul"] = { fg = "#a50e0e" },
  ["GitSignsUntracked"] = { fg = "#0d652d" },
  ["GitSignsUntrackedNr"] = { fg = "#0d652d" },
  ["GitSignsUntrackedCul"] = { fg = "#0d652d" },
  ["GitSignsStagedAdd"] = { fg = "#0d652d", bold = true },
  ["GitSignsStagedAddNr"] = { fg = "#0d652d", bold = true },
  ["GitSignsStagedAddCul"] = { fg = "#0d652d", bold = true },
  ["GitSignsStagedChange"] = { fg = "#174ea6", bold = true },
  ["GitSignsStagedChangeNr"] = { fg = "#174ea6", bold = true },
  ["GitSignsStagedChangeCul"] = { fg = "#174ea6", bold = true },
  ["GitSignsStagedChangedelete"] = { fg = "#174ea6", bold = true },
  ["GitSignsStagedChangedeleteNr"] = { fg = "#174ea6", bold = true },
  ["GitSignsStagedChangedeleteCul"] = { fg = "#174ea6", bold = true },
  ["GitSignsStagedDelete"] = { fg = "#a50e0e", bold = true },
  ["GitSignsStagedDeleteNr"] = { fg = "#a50e0e", bold = true },
  ["GitSignsStagedDeleteCul"] = { fg = "#a50e0e", bold = true },
  ["GitSignsStagedTopdelete"] = { fg = "#a50e0e", bold = true },
  ["GitSignsStagedTopdeleteNr"] = { fg = "#a50e0e", bold = true },
  ["GitSignsStagedTopdeleteCul"] = { fg = "#a50e0e", bold = true },
  ["GitSignsStagedUntracked"] = { fg = "#0d652d", bold = true },
  ["GitSignsStagedUntrackedNr"] = { fg = "#0d652d", bold = true },
  ["GitSignsStagedUntrackedCul"] = { fg = "#0d652d", bold = true },
  ["LuaLineDiffAdd"] = { fg = "#0d652d" },
  ["LuaLineDiffChange"] = { fg = "#934900" },
  ["LuaLineDiffDelete"] = { fg = "#a50e0e" },
  ["LspInlayHint"] = { fg = "#595d62" },
  ["LspCodeLens"] = { fg = "#595d62" },
  ["LspCodeLensSeparator"] = { fg = "#595d62" },
  ["BlinkCmpGhostText"] = { fg = "#595d62" },
  ["BlinkCmpLabelDeprecated"] = { fg = "#595d62", strikethrough = true },
  ["BlinkCmpLabelMatch"] = { fg = "#174ea6", bold = true },
  ["SnacksPickerDir"] = { fg = "#595d62" },
  ["SnacksPickerDimmed"] = { fg = "#595d62" },
  ["SnacksPickerBufFlags"] = { fg = "#595d62" },
  ["SnacksPickerGitStatusAdded"] = { fg = "#0d652d" },
  ["SnacksPickerGitStatusUntracked"] = { fg = "#202124" },
  ["SnacksIndent"] = { fg = "#595d62" },
  ["SnacksIndentScope"] = { fg = "#595d62" },
  ["TodoFgFIX"] = { fg = "#a50e0e" },
  ["TodoBgFIX"] = { fg = "#ffffff", bg = "#a50e0e", bold = true },
  ["TodoSignFIX"] = { fg = "#a50e0e" },
  ["TodoFgTODO"] = { fg = "#681da8" },
  ["TodoBgTODO"] = { fg = "#ffffff", bg = "#681da8", bold = true },
  ["TodoSignTODO"] = { fg = "#681da8" },
  ["TodoFgHACK"] = { fg = "#934900" },
  ["TodoBgHACK"] = { fg = "#202124", bg = "#e37400", bold = true },
  ["TodoSignHACK"] = { fg = "#934900" },
  ["TodoFgWARN"] = { fg = "#934900" },
  ["TodoBgWARN"] = { fg = "#202124", bg = "#e37400", bold = true },
  ["TodoSignWARN"] = { fg = "#934900" },
  ["TodoFgPERF"] = { fg = "#681da8" },
  ["TodoBgPERF"] = { fg = "#ffffff", bg = "#681da8", bold = true },
  ["TodoSignPERF"] = { fg = "#681da8" },
  ["TodoFgNOTE"] = { fg = "#202124" },
  ["TodoBgNOTE"] = { fg = "#ffffff", bg = "#202124", bold = true },
  ["TodoSignNOTE"] = { fg = "#202124" },
  ["TodoFgTEST"] = { fg = "#202124" },
  ["TodoBgTEST"] = { fg = "#ffffff", bg = "#202124", bold = true },
  ["TodoSignTEST"] = { fg = "#202124" },
  ["MiniIconsAzure"] = { fg = "#174ea6" },
  ["MiniIconsBlue"] = { fg = "#174ea6" },
  ["MiniIconsCyan"] = { fg = "#00636d" },
  ["MiniIconsGreen"] = { fg = "#0d652d" },
  ["MiniIconsGrey"] = { fg = "#202124" },
  ["MiniIconsOrange"] = { fg = "#934900" },
  ["MiniIconsPurple"] = { fg = "#681da8" },
  ["MiniIconsRed"] = { fg = "#a50e0e" },
  ["MiniIconsYellow"] = { fg = "#934900", bold = true },
  ["OkMsg"] = { fg = "#0d652d" },
  ["VenvSelectActiveVenv"] = { fg = "#202124" },
  ["NeotestPassed"] = { fg = "#0d652d" },
  ["NeotestFailed"] = { fg = "#a50e0e" },
  ["NeotestRunning"] = { fg = "#934900", bold = true },
  ["NeotestWatching"] = { fg = "#174ea6" },
  ["NeotestSkipped"] = { fg = "#595d62" },
  ["NeotestUnknown"] = { fg = "#595d62" },
  ["NeotestMarked"] = { fg = "#934900", bold = true },
  ["NeotestTarget"] = { fg = "#174ea6" },
  ["NeotestNamespace"] = { fg = "#681da8" },
  ["NeotestFile"] = { fg = "#202124" },
  ["NeotestDir"] = { fg = "#174ea6" },
  ["NeotestAdapterName"] = { fg = "#681da8" },
  ["NeotestWinSelect"] = { fg = "#202124", bold = true },
  ["NeotestExpandMarker"] = { fg = "#595d62" },
  ["NeotestIndent"] = { fg = "#595d62" },
  ["GrugFarResultsAddIndicator"] = { fg = "#0d652d" },
  ["GrugFarResultsChangeIndicator"] = { fg = "#934900" },
  ["GrugFarResultsRemoveIndicator"] = { fg = "#a50e0e" },
}

for name, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, name, spec)
end

-- Link the full standard LSP token vocabulary; modifiers keep the token's colour.
local semantic = {
  namespace = "@module", type = "@type", class = "@type", enum = "@type",
  interface = "@type", struct = "@type", typeParameter = "@type",
  parameter = "@variable.parameter", variable = "@variable", property = "@property",
  enumMember = "@constant", event = "@type", ["function"] = "@function",
  method = "@function.method", macro = "@function.macro", keyword = "@keyword",
  modifier = "@keyword", comment = "@comment", string = "@string", number = "@number",
  regexp = "@string.regexp", operator = "@operator", decorator = "@attribute",
}
for token, target in pairs(semantic) do
  vim.api.nvim_set_hl(0, "@lsp.type." .. token, { link = target })
end
