-- fmind — generated by render.py, do not edit
-- source: palettes/fmind.yaml
--
-- Drop into colors/ on the runtimepath, then `colorscheme fmind`.
-- Italic is never set: FiraCode ships no italic face, so it would be
-- synthesised by slanting upright glyphs.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.termguicolors = true
vim.o.background = "dark"
vim.g.colors_name = "fmind"

vim.g.terminal_color_0 = "#243c29"
vim.g.terminal_color_1 = "#f63a4b"
vim.g.terminal_color_2 = "#d4fed2"
vim.g.terminal_color_3 = "#ce9402"
vim.g.terminal_color_4 = "#35ab24"
vim.g.terminal_color_5 = "#d395fb"
vim.g.terminal_color_6 = "#2ad7f5"
vim.g.terminal_color_7 = "#a4a9a1"
vim.g.terminal_color_8 = "#6c776a"
vim.g.terminal_color_9 = "#f69579"
vim.g.terminal_color_10 = "#26fed9"
vim.g.terminal_color_11 = "#f6bf46"
vim.g.terminal_color_12 = "#029fd7"
vim.g.terminal_color_13 = "#d045ee"
vim.g.terminal_color_14 = "#17bfa6"
vim.g.terminal_color_15 = "#f1f8f2"

local groups = {
  ["Normal"] = { fg = "#56ff40", bg = "#000000" },
  ["NormalFloat"] = { fg = "#56ff40", bg = "#151b14" },
  ["FloatBorder"] = { fg = "#6c776a", bg = "#151b14" },
  ["CursorLine"] = { bg = "#111211" },
  ["CursorLineNr"] = { fg = "#56ff40", bold = true },
  ["LineNr"] = { fg = "#7a7d7a" },
  ["Visual"] = { bg = "#222b22" },
  ["Search"] = { fg = "#000000", bg = "#ce9402" },
  ["IncSearch"] = { fg = "#000000", bg = "#f69579" },
  ["MatchParen"] = { fg = "#f69579", bold = true },
  ["Pmenu"] = { fg = "#56ff40", bg = "#151b14" },
  ["PmenuSel"] = { bg = "#222b22", bold = true },
  ["StatusLine"] = { fg = "#56ff40", bg = "#151b14" },
  ["WinSeparator"] = { fg = "#6c776a" },
  ["Whitespace"] = { fg = "#7a7d7a" },
  ["Folded"] = { fg = "#6c776a", bg = "#151b14" },
  ["Title"] = { fg = "#35ab24", bold = true },
  ["Directory"] = { fg = "#35ab24" },
  ["Cursor"] = { fg = "#000000", bg = "#26fed9" },
  ["Comment"] = { fg = "#6c776a" },
  ["Identifier"] = { fg = "#56ff40" },
  ["Function"] = { fg = "#35ab24", bold = true },
  ["Statement"] = { fg = "#d395fb", bold = true },
  ["Keyword"] = { fg = "#d395fb", bold = true },
  ["Conditional"] = { fg = "#d395fb", bold = true },
  ["Repeat"] = { fg = "#d395fb", bold = true },
  ["Operator"] = { fg = "#a4a9a1" },
  ["Delimiter"] = { fg = "#a4a9a1" },
  ["Type"] = { fg = "#2ad7f5" },
  ["String"] = { fg = "#d4fed2" },
  ["Character"] = { fg = "#d4fed2" },
  ["Number"] = { fg = "#ce9402" },
  ["Float"] = { fg = "#ce9402" },
  ["Boolean"] = { fg = "#f6bf46" },
  ["Constant"] = { fg = "#f6bf46" },
  ["Special"] = { fg = "#26fed9" },
  ["PreProc"] = { fg = "#d045ee" },
  ["Error"] = { fg = "#f63a4b", bold = true },
  ["ErrorMsg"] = { fg = "#f63a4b", bold = true },
  ["WarningMsg"] = { fg = "#f69579" },
  ["Todo"] = { fg = "#000000", bg = "#f69579", bold = true },
  ["@variable"] = { fg = "#56ff40" },
  ["@variable.parameter"] = { fg = "#029fd7" },
  ["@variable.member"] = { fg = "#17bfa6" },
  ["@property"] = { fg = "#17bfa6" },
  ["@field"] = { fg = "#17bfa6" },
  ["@function"] = { fg = "#35ab24", bold = true },
  ["@function.call"] = { fg = "#35ab24", bold = true },
  ["@function.method"] = { fg = "#35ab24", bold = true },
  ["@function.method.call"] = { fg = "#35ab24", bold = true },
  ["@function.builtin"] = { fg = "#d045ee" },
  ["@constructor"] = { fg = "#2ad7f5" },
  ["@keyword"] = { fg = "#d395fb", bold = true },
  ["@keyword.function"] = { fg = "#d395fb", bold = true },
  ["@keyword.return"] = { fg = "#d395fb", bold = true },
  ["@keyword.import"] = { fg = "#d395fb", bold = true },
  ["@keyword.operator"] = { fg = "#d395fb", bold = true },
  ["@keyword.exception"] = { fg = "#f63a4b", bold = true },
  ["@type"] = { fg = "#2ad7f5" },
  ["@type.builtin"] = { fg = "#2ad7f5" },
  ["@module"] = { fg = "#17bfa6" },
  ["@string"] = { fg = "#d4fed2" },
  ["@string.escape"] = { fg = "#26fed9" },
  ["@string.special"] = { fg = "#26fed9" },
  ["@number"] = { fg = "#ce9402" },
  ["@boolean"] = { fg = "#f6bf46" },
  ["@constant"] = { fg = "#f6bf46" },
  ["@constant.builtin"] = { fg = "#f6bf46" },
  ["@comment"] = { fg = "#6c776a" },
  ["@comment.error"] = { fg = "#f63a4b", bold = true },
  ["@comment.warning"] = { fg = "#f69579" },
  ["@punctuation.bracket"] = { fg = "#a4a9a1" },
  ["@punctuation.delimiter"] = { fg = "#a4a9a1" },
  ["@punctuation.special"] = { fg = "#26fed9" },
  ["@operator"] = { fg = "#a4a9a1" },
  ["@attribute"] = { fg = "#d045ee" },
  ["@lsp.type.parameter"] = { fg = "#029fd7" },
  ["@lsp.type.property"] = { fg = "#17bfa6" },
  ["@lsp.type.variable"] = { fg = "#56ff40" },
  ["@lsp.type.class"] = { fg = "#2ad7f5" },
  ["@lsp.type.function"] = { fg = "#35ab24", bold = true },
  ["@lsp.type.method"] = { fg = "#35ab24", bold = true },
  ["@lsp.type.keyword"] = { fg = "#d395fb", bold = true },
  ["DiagnosticError"] = { fg = "#f63a4b" },
  ["DiagnosticWarn"] = { fg = "#f69579" },
  ["DiagnosticInfo"] = { fg = "#2ad7f5" },
  ["DiagnosticHint"] = { fg = "#17bfa6" },
  ["DiagnosticOk"] = { fg = "#d4fed2" },
  ["DiagnosticUnderlineError"] = { sp = "#f63a4b", undercurl = true },
  ["DiagnosticUnderlineWarn"] = { sp = "#f69579", undercurl = true },
  ["DiffAdd"] = { bg = "#1a211a" },
  ["DiffDelete"] = { bg = "#43080e" },
  ["DiffChange"] = { bg = "#2c1d00" },
  ["DiffText"] = { bg = "#382600" },
  ["Added"] = { fg = "#d4fed2" },
  ["Removed"] = { fg = "#f63a4b" },
  ["Changed"] = { fg = "#ce9402" },
}

for name, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, name, spec)
end
