# Fmind light color overrides for Powerlevel10k
typeset -g POWERLEVEL9K_DIR_BACKGROUND='#d2e3fc'
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#202124'
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#595d62'
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#174ea6'

typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='#ceead6'
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#0d652d'
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='#feefc3'
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#934900'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='#fad2cf'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#a50e0e'

typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND='#ceead6'
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND='#0d652d'
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND='#fad2cf'
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#a50e0e'

typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#174ea6'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#a50e0e'
