;;; https://www.gnu.org/software/emacs/manual/html_node/elisp/Custom-Themes.html
;;; fmind-theme.el --- Fmind light colors -*- lexical-binding: t; -*-
(deftheme fmind "Readable light colors for code and text.")
(custom-theme-set-faces
 'fmind
 '(default ((t (:foreground "#202124" :background "#ffffff"))))
 '(cursor ((t (:background "#4285f4"))))
 '(fringe ((t (:foreground "#595d62" :background "#ffffff"))))
 '(region ((t (:background "#d2e3fc"))))
 '(highlight ((t (:background "#d2e3fc"))))
 '(hl-line ((t (:background "#f1f3f4"))))
 '(secondary-selection ((t (:background "#feefc3"))))
 '(minibuffer-prompt ((t (:foreground "#174ea6" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#595d62" :slant normal))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#595d62" :slant normal))))
 '(font-lock-doc-face ((t (:foreground "#595d62" :slant normal))))
 '(font-lock-keyword-face ((t (:foreground "#174ea6" :slant normal :weight bold))))
 '(font-lock-function-name-face ((t (:foreground "#174ea6" :slant normal))))
 '(font-lock-function-call-face ((t (:foreground "#174ea6" :slant normal))))
 '(font-lock-variable-name-face ((t (:foreground "#202124" :slant normal))))
 '(font-lock-variable-use-face ((t (:foreground "#202124" :slant normal))))
 '(font-lock-type-face ((t (:foreground "#681da8" :slant normal))))
 '(font-lock-builtin-face ((t (:foreground "#681da8" :slant normal))))
 '(font-lock-preprocessor-face ((t (:foreground "#681da8" :slant normal))))
 '(font-lock-constant-face ((t (:foreground "#934900" :slant normal))))
 '(font-lock-number-face ((t (:foreground "#934900" :slant normal))))
 '(font-lock-string-face ((t (:foreground "#0d652d" :slant normal))))
 '(font-lock-operator-face ((t (:foreground "#202124" :slant normal))))
 '(font-lock-punctuation-face ((t (:foreground "#202124" :slant normal))))
 '(font-lock-warning-face ((t (:foreground "#a50e0e" :slant normal))))
 '(error ((t (:foreground "#a50e0e"))))
 '(warning ((t (:foreground "#934900"))))
 '(success ((t (:foreground "#0d652d"))))
 '(shadow ((t (:foreground "#595d62"))))
 '(link ((t (:foreground "#174ea6"))))
 '(link-visited ((t (:foreground "#681da8"))))
 '(mode-line ((t (:foreground "#202124" :background "#d2e3fc" :weight bold :box nil))))
 '(mode-line-inactive ((t (:foreground "#595d62" :background "#f1f3f4" :box nil))))
 '(header-line ((t (:foreground "#202124" :background "#f1f3f4"))))
 '(line-number ((t (:foreground "#595d62" :background "#ffffff"))))
 '(line-number-current-line ((t (:foreground "#174ea6" :background "#f1f3f4"))))
 '(isearch ((t (:foreground "#202124" :background "#fbbc04"))))
 '(isearch-fail ((t (:foreground "#a50e0e" :background "#fad2cf"))))
 '(lazy-highlight ((t (:foreground "#202124" :background "#feefc3"))))
 '(match ((t (:foreground "#202124" :background "#feefc3"))))
 '(show-paren-match ((t (:foreground "#202124" :background "#feefc3"))))
 '(show-paren-mismatch ((t (:foreground "#a50e0e" :background "#fad2cf"))))
 '(completions-common-part ((t (:foreground "#174ea6"))))
 '(completions-first-difference ((t (:foreground "#681da8"))))
 '(completions-highlight ((t (:foreground "#202124" :background "#d2e3fc"))))
 '(tooltip ((t (:foreground "#202124" :background "#f1f3f4"))))
 '(diff-added ((t (:foreground "#0d652d" :background "#ceead6"))))
 '(diff-removed ((t (:foreground "#a50e0e" :background "#fad2cf"))))
 '(diff-changed ((t (:foreground "#934900" :background "#feefc3"))))
 '(diff-refine-added ((t (:foreground "#0d652d" :background "#ceead6"))))
 '(diff-refine-removed ((t (:foreground "#a50e0e" :background "#fad2cf"))))
 '(diff-header ((t (:foreground "#174ea6" :background "#f1f3f4"))))
 '(diff-file-header ((t (:foreground "#174ea6" :background "#f1f3f4"))))
 '(dired-directory ((t (:foreground "#174ea6"))))
 '(dired-symlink ((t (:foreground "#00636d"))))
 '(dired-marked ((t (:foreground "#0d652d"))))
 '(dired-flagged ((t (:foreground "#a50e0e"))))
 '(org-level-1 ((t (:foreground "#174ea6" :weight bold))))
 '(org-level-2 ((t (:foreground "#0d652d" :weight bold))))
 '(org-level-3 ((t (:foreground "#681da8"))))
 '(org-level-4 ((t (:foreground "#934900"))))
 '(org-code ((t (:foreground "#174ea6"))))
 '(org-verbatim ((t (:foreground "#174ea6"))))
 '(org-block ((t (:foreground "#202124" :background "#f1f3f4"))))
 '(org-block-begin-line ((t (:foreground "#595d62" :background "#f1f3f4"))))
 '(org-block-end-line ((t (:foreground "#595d62" :background "#f1f3f4"))))
 '(org-todo ((t (:foreground "#a50e0e"))))
 '(org-done ((t (:foreground "#0d652d"))))
 '(org-date ((t (:foreground "#00636d"))))
 '(org-link ((t (:foreground "#174ea6"))))
)
(provide-theme 'fmind)
