# https://codeberg.org/dnkl/fuzzel/src/branch/master/doc/fuzzel.ini.5.scd
[colors]
background=ffffffff
text=202124ff
message=595d62ff
prompt=174ea6ff
placeholder=595d62ff
input=202124ff
match=934900ff
selection=d2e3fcff
selection-text=202124ff
selection-match=934900ff
counter=595d62ff
border=174ea6ff
