# :schema https://yazi-rs.github.io/schemas/theme.json
# Docs: https://yazi-rs.github.io/docs/configuration/theme/

[app]
overall = { fg = "#202124", bg = "#ffffff" }

[mgr]
cwd = { fg = "#174ea6", italic = false, reversed = false }
border_style = { fg = "#595d62", italic = false, reversed = false }
find_keyword = { fg = "#202124", italic = false, reversed = false, bg = "#e37400", bold = true }
find_position = { fg = "#174ea6", italic = false, reversed = false }
symlink_target = { fg = "#595d62", italic = false, reversed = false }
marker_copied = { fg = "#34a853", italic = false, reversed = false, bg = "#34a853" }
marker_cut = { fg = "#ea4335", italic = false, reversed = false, bg = "#ea4335" }
marker_marked = { fg = "#4285f4", italic = false, reversed = false, bg = "#4285f4" }
marker_selected = { fg = "#e37400", italic = false, reversed = false, bg = "#e37400" }
count_copied = { fg = "#202124", italic = false, reversed = false, bg = "#34a853" }
count_cut = { fg = "#ffffff", italic = false, reversed = false, bg = "#a50e0e" }
count_selected = { fg = "#202124", italic = false, reversed = false, bg = "#fbbc04" }
syntect_theme = "~/.config/bat/themes/fmind.tmTheme"

[indicator]
parent = { fg = "#202124", italic = false, reversed = false, bg = "#d2e3fc", bold = true }
current = { fg = "#202124", italic = false, reversed = false, bg = "#d2e3fc", bold = true }
preview = { fg = "#202124", italic = false, reversed = false, bg = "#d2e3fc", bold = true }

[tabs]
active = { fg = "#202124", italic = false, reversed = false, bg = "#fbbc04", bold = true }
inactive = { fg = "#202124", italic = false, reversed = false, bg = "#4285f4" }

[mode]
normal_main = { fg = "#202124", italic = false, reversed = false, bg = "#4285f4", bold = true }
normal_alt = { fg = "#202124", italic = false, reversed = false, bg = "#ffffff" }
select_main = { fg = "#202124", italic = false, reversed = false, bg = "#34a853", bold = true }
select_alt = { fg = "#202124", italic = false, reversed = false, bg = "#ffffff" }
unset_main = { fg = "#202124", italic = false, reversed = false, bg = "#e37400", bold = true }
unset_alt = { fg = "#202124", italic = false, reversed = false, bg = "#ffffff" }

[status]
overall = { fg = "#202124", italic = false, reversed = false, bg = "#f1f3f4" }
perm_type = { fg = "#174ea6", italic = false, reversed = false }
perm_read = { fg = "#0d652d", italic = false, reversed = false }
perm_write = { fg = "#934900", italic = false, reversed = false }
perm_exec = { fg = "#0d652d", italic = false, reversed = false }
perm_sep = { fg = "#595d62", italic = false, reversed = false }
progress_label = { fg = "#202124", italic = false, reversed = false, bg = "#ffffff" }
progress_normal = { fg = "#174ea6", italic = false, reversed = false, bg = "#f1f3f4" }
progress_error = { fg = "#a50e0e", italic = false, reversed = false, bg = "#f1f3f4" }

[which]
mask = { bg = "#f1f3f4" }
border = { fg = "#174ea6", italic = false, reversed = false }
cand = { fg = "#174ea6", italic = false, reversed = false }
rest = { fg = "#595d62", italic = false, reversed = false }
desc = { fg = "#202124", italic = false, reversed = false, bg = "#ffffff" }
separator_style = { fg = "#595d62", italic = false, reversed = false }

[confirm]
border = { fg = "#174ea6", italic = false, reversed = false }
title = { fg = "#174ea6", italic = false, reversed = false }
body = { fg = "#202124", italic = false, reversed = false, bg = "#ffffff" }
list = { fg = "#202124", italic = false, reversed = false, bg = "#ffffff" }
btn_yes = { fg = "#202124", italic = false, reversed = false, bg = "#d2e3fc", bold = true }
btn_no = { fg = "#202124", italic = false, reversed = false, bg = "#ffffff" }

[spot]
border = { fg = "#174ea6", italic = false, reversed = false }
title = { fg = "#174ea6", italic = false, reversed = false }
tbl_col = { fg = "#174ea6", italic = false, reversed = false }
tbl_cell = { fg = "#202124", italic = false, reversed = false, bg = "#d2e3fc", bold = true }

[notify]
title_info = { fg = "#00636d", italic = false, reversed = false }
title_warn = { fg = "#934900", italic = false, reversed = false }
title_error = { fg = "#a50e0e", italic = false, reversed = false }

[pick]
border = { fg = "#174ea6", italic = false, reversed = false }
active = { fg = "#202124", italic = false, reversed = false, bg = "#d2e3fc", bold = true }
inactive = { fg = "#202124", italic = false, reversed = false, bg = "#ffffff" }

[input]
border = { fg = "#174ea6", italic = false, reversed = false }
title = { fg = "#174ea6", italic = false, reversed = false }
value = { fg = "#202124", italic = false, reversed = false, bg = "#ffffff" }
selected = { fg = "#202124", italic = false, reversed = false, bg = "#d2e3fc", bold = true }

[cmp]
border = { fg = "#174ea6", italic = false, reversed = false }
active = { fg = "#202124", italic = false, reversed = false, bg = "#d2e3fc", bold = true }
inactive = { fg = "#202124", italic = false, reversed = false, bg = "#ffffff" }

[tasks]
border = { fg = "#174ea6", italic = false, reversed = false }
title = { fg = "#174ea6", italic = false, reversed = false }
hovered = { fg = "#202124", italic = false, reversed = false, bg = "#d2e3fc", bold = true }

[help]
border = { fg = "#174ea6", italic = false, reversed = false }
chord = { fg = "#174ea6", italic = false, reversed = false }
action = { fg = "#202124", italic = false, reversed = false, bg = "#ffffff" }
hovered = { fg = "#202124", italic = false, reversed = false, bg = "#d2e3fc", bold = true }

[filetype]
rules = [{ url = "*/", fg = "#174ea6" }, { url = "*", is = "exec", fg = "#0d652d" }, { url = "*", fg = "#202124" }]
