# https://i3wm.org/docs/userguide.html#client_colors
# class                 border  background text    indicator child_border
client.focused          #174ea6 #d2e3fc    #202124 #4285f4   #174ea6
client.focused_inactive #9aa0a6 #f1f3f4    #595d62 #9aa0a6   #9aa0a6
client.unfocused        #9aa0a6 #f1f3f4    #595d62 #9aa0a6   #9aa0a6
client.urgent           #a50e0e #fad2cf    #a50e0e #ea4335   #a50e0e
client.placeholder      #9aa0a6 #f1f3f4    #595d62 #9aa0a6   #9aa0a6
client.background       #ffffff
