[General]
name = Fmind
author = Médéric Hurier

[Colors]
background = #ffffff
text = #202124
sidebar = #f1f3f4
border = #9aa0a6
selection = #d2e3fc
heading = #174ea6
comment = #595d62
highlight = #feefc3
