# https://dunst-project.org/documentation/
[global]
frame_color = "#9aa0a6"
separator_color = "#9aa0a6"
highlight = "#174ea6"

[urgency_low]
background = "#f1f3f4"
foreground = "#595d62"
frame_color = "#9aa0a6"

[urgency_normal]
background = "#ffffff"
foreground = "#202124"
frame_color = "#174ea6"

[urgency_critical]
background = "#fad2cf"
foreground = "#a50e0e"
frame_color = "#a50e0e"
