# https://gnome-terminator.readthedocs.io/en/latest/config.html
[profiles]
  [[fmind]]
    use_theme_colors = False
    background_color = "#ffffff"
    foreground_color = "#202124"
    cursor_color = "#4285f4"
    palette = "#202124:#a50e0e:#0d652d:#934900:#174ea6:#681da8:#00636d:#202124:#595d62:#a50e0e:#0d652d:#934900:#174ea6:#681da8:#00636d:#202124"
