[theme]
background = "#ffffff"
primary = "#202124"
secondary = "#595d62"
title = "#174ea6"
playing = "#174ea6"
playing_selected = "#174ea6"
playing_bg = "#ffffff"
highlight = "#202124"
highlight_bg = "#d2e3fc"
error = "#ffffff"
error_bg = "#a50e0e"
statusbar = "#ffffff"
statusbar_progress = "#174ea6"
statusbar_bg = "#f1f3f4"
cmdline = "#202124"
cmdline_bg = "#ffffff"
