# https://sw.kovidgoyal.net/kitty/conf/#color-scheme
background #ffffff
foreground #202124
cursor #4285f4
cursor_text_color #202124
selection_foreground #202124
selection_background #d2e3fc
active_border_color #174ea6
inactive_border_color #9aa0a6
bell_border_color #e37400
active_tab_foreground #202124
active_tab_background #fbbc04
active_tab_font_style bold
inactive_tab_foreground #595d62
inactive_tab_background #f1f3f4
inactive_tab_font_style normal
tab_bar_background #f1f3f4
url_color #174ea6
mark1_foreground #202124
mark1_background #feefc3
mark2_foreground #202124
mark2_background #ceead6
mark3_foreground #202124
mark3_background #fad2cf
color0 #202124
color1 #a50e0e
color2 #0d652d
color3 #934900
color4 #174ea6
color5 #681da8
color6 #00636d
color7 #202124
color8 #595d62
color9 #a50e0e
color10 #0d652d
color11 #934900
color12 #174ea6
color13 #681da8
color14 #00636d
color15 #202124
