# https://www.geany.org/manual/current/index.html#color-schemes-menu
[theme_info]
name=Fmind
description=Fmind light editor colors
version=1.0
author=Fmind
url=https://github.com/fmind/theme

[named_styles]
default=0x202124;0xffffff;false;false
identifier=0x202124;0xffffff;false;false
identifier_1=0x202124;0xffffff;false;false
identifier_2=0x202124;0xffffff;false;false
identifier_3=0x202124;0xffffff;false;false
identifier_4=0x202124;0xffffff;false;false
parameter=0x202124;0xffffff;false;false
operator=0x202124;0xffffff;false;false
other=0x202124;0xffffff;false;false
entity=0x202124;0xffffff;false;false
label=0x202124;0xffffff;false;false
comment=0x595d62;0xffffff;false;false
comment_doc=0x595d62;0xffffff;false;false
comment_line=0x595d62;0xffffff;false;false
comment_line_doc=0x595d62;0xffffff;false;false
comment_doc_keyword=0x595d62;0xffffff;false;false
comment_doc_keyword_error=0xa50e0e;0xfad2cf;false;false
error=0xa50e0e;0xfad2cf;false;false
string_eol=0xa50e0e;0xfad2cf;false;false
number=0x934900;0xffffff;false;false
number_1=0x934900;0xffffff;false;false
number_2=0x934900;0xffffff;false;false
number_3=0x934900;0xffffff;false;false
type=0x681da8;0xffffff;false;false
class=0x681da8;0xffffff;false;false
annotation=0x681da8;0xffffff;false;false
decorator=0x681da8;0xffffff;false;false
macro=0x681da8;0xffffff;false;false
preprocessor=0x681da8;0xffffff;false;false
function=0x174ea6;0xffffff;true;false
keyword=0x174ea6;0xffffff;true;false
keyword_1=0x174ea6;0xffffff;true;false
keyword_2=0x174ea6;0xffffff;true;false
keyword_3=0x174ea6;0xffffff;true;false
keyword_4=0x174ea6;0xffffff;true;false
tag=0x174ea6;0xffffff;true;false
tag_unknown=0x174ea6;0xffffff;true;false
tag_end=0x174ea6;0xffffff;true;false
string=0x0d652d;0xffffff;false;false
string_1=0x0d652d;0xffffff;false;false
string_2=0x0d652d;0xffffff;false;false
string_3=0x0d652d;0xffffff;false;false
string_4=0x0d652d;0xffffff;false;false
character=0x0d652d;0xffffff;false;false
backticks=0x0d652d;0xffffff;false;false
here_doc=0x0d652d;0xffffff;false;false
regex=0x0d652d;0xffffff;false;false
value=0x0d652d;0xffffff;false;false
attribute=0x202124;0xffffff;false;false
attribute_unknown=0x202124;0xffffff;false;false
selection=0x202124;0xd2e3fc;true;true
current_line=0x202124;0xf1f3f4;true;false
brace_good=0x174ea6;0xd2e3fc;true;false
brace_bad=0xa50e0e;0xfad2cf;true;false
margin_line_number=0x595d62;0xffffff;false;false
margin_folding=0x595d62;0xffffff;false;false
fold_symbol_highlight=0x174ea6;0xffffff;false;false
indent_guide=0x9aa0a6;0xffffff;false;false
white_space=0x9aa0a6;0xffffff;false;false
caret=0x174ea6;0xffffff;false;false
marker_line=0x202124;0xfeefc3;false;false
marker_search=0x202124;0xfeefc3;false;false
marker_mark=0x202124;0xceead6;false;false
call_tips=0x202124;0xffffff;true;true
line_added=0x0d652d;0xceead6;false;false
line_removed=0xa50e0e;0xfad2cf;false;false
line_changed=0x934900;0xfeefc3;false;false
