# Fmind Omarchy colors
$background = rgb(ffffff)
$foreground = rgb(202124)
$accent     = rgb(174ea6)
$surface    = rgb(f1f3f4)
$selection  = rgb(d2e3fc)

general {
    col.active_border = rgba(174ea6ee)
    col.inactive_border = rgba(f1f3f4aa)
}
