; https://github.com/polybar/polybar/wiki/Configuration
[colors]
background = #ffffff
background-alt = #d2e3fc
foreground = #202124
primary = #174ea6
secondary = #00636d
alert = #a50e0e
disabled = #595d62
