-- fmind — generated by render.py, do not edit
-- source: palettes/fmind.yaml
--
-- Drop into lua/lualine/themes/ under the Neovim config directory. lualine's
-- `auto` theme loads this by vim.g.colors_name before it derives anything,
-- so nothing has to be configured for it to take effect.

local ground = {
  panel = "#1d1f1d",
  sel = "#2b2c2b",
}

return {
  normal = {
    a = { bg = ground.sel, fg = "#56ff40", gui = 'bold' },
    b = { bg = ground.panel, fg = "#a1a6a0" },
    c = { bg = ground.panel, fg = "#7e8a7b" },
  },
  insert = {
    a = { bg = ground.sel, fg = "#26fed9", gui = 'bold' },
    b = { bg = ground.panel, fg = "#a1a6a0" },
    c = { bg = ground.panel, fg = "#7e8a7b" },
  },
  visual = {
    a = { bg = ground.sel, fg = "#9578ff", gui = 'bold' },
    b = { bg = ground.panel, fg = "#a1a6a0" },
    c = { bg = ground.panel, fg = "#7e8a7b" },
  },
  replace = {
    a = { bg = ground.sel, fg = "#f63a4b", gui = 'bold' },
    b = { bg = ground.panel, fg = "#a1a6a0" },
    c = { bg = ground.panel, fg = "#7e8a7b" },
  },
  command = {
    a = { bg = ground.sel, fg = "#f8cc28", gui = 'bold' },
    b = { bg = ground.panel, fg = "#a1a6a0" },
    c = { bg = ground.panel, fg = "#7e8a7b" },
  },
  terminal = {
    a = { bg = ground.sel, fg = "#029fd7", gui = 'bold' },
    b = { bg = ground.panel, fg = "#a1a6a0" },
    c = { bg = ground.panel, fg = "#7e8a7b" },
  },
  inactive = {
    a = { bg = ground.panel, fg = "#7e8a7b", gui = 'bold' },
    b = { bg = ground.panel, fg = "#7e8a7b" },
    c = { bg = ground.panel, fg = "#7e8a7b" },
  },
}
