# https://github.com/lxde/lxterminal/blob/master/src/setting.c
[general]
bgcolor=#ffffff
fgcolor=#202124
color_preset=Custom
boldbright=false
palette_color_0=#202124
palette_color_1=#a50e0e
palette_color_2=#0d652d
palette_color_3=#934900
palette_color_4=#174ea6
palette_color_5=#681da8
palette_color_6=#00636d
palette_color_7=#202124
palette_color_8=#595d62
palette_color_9=#a50e0e
palette_color_10=#0d652d
palette_color_11=#934900
palette_color_12=#174ea6
palette_color_13=#681da8
palette_color_14=#00636d
palette_color_15=#202124
