# https://github.com/francma/wob/blob/master/wob.ini.5.scd
border_color = #174ea6
background_color = #ffffff
bar_color = #174ea6
overflow_border_color = #a50e0e
overflow_background_color = #fad2cf
overflow_bar_color = #a50e0e
